;;; auto-maintained by forms-oracle.lisp — pinned subtest
;;; denominators (file . most-subtests-ever-seen).
(("HTMLFieldSetElement.html" . 4) ("button-checkvalidity.html" . 1)
 ("button-events.html" . 9) ("button-labels.html" . 1)
 ("button-setcustomvalidity.html" . 1)
 ("button-type-enumerated-ascii-case-insensitive.html" . 2)
 ("button-type.html" . 2) ("button-validation.html" . 6)
 ("button-validationmessage.html" . 1) ("button-validity.html" . 1)
 ("button-willvalidate-readonly-attribute.html" . 1)
 ("button-willvalidate.html" . 1) ("change-to-empty-value.html" . 1)
 ("clone.html" . 19) ("color.html" . 27)
 ("common-HTMLOptionsCollection-add.html" . 3)
 ("common-HTMLOptionsCollection-namedItem.html" . 6)
 ("common-HTMLOptionsCollection.html" . 8)
 ("datetime-local-valueasdate.html" . 1) ("datetime-local.html" . 17)
 ("defaultSelection.html" . 6) ("disabled-001.html" . 5)
 ("disabled-003.html" . 2) ("disabled-elements-01.html" . 16)
 ("fieldset-checkvalidity.html" . 1) ("fieldset-intrinsic-size.html" . 6)
 ("fieldset-setcustomvalidity.html" . 1)
 ("fieldset-validationmessage.html" . 1) ("fieldset-validity.html" . 1)
 ("fieldset-willvalidate.html" . 1) ("files.html" . 24)
 ("form-action-reflection-with-base-url.html" . 3)
 ("form-action-reflection.html" . 3)
 ("form-action-submission-with-base-url.html" . 3)
 ("form-action-submission.html" . 3) ("form-action.html" . 1)
 ("form-autocomplete.html" . 67) ("form-checkvalidity.html" . 1)
 ("form-controls-id-removal-crash.html" . 1)
 ("form-controls-nested-id-crash.html" . 1) ("form-elements-filter.html" . 2)
 ("form-elements-interfaces-01.html" . 3) ("form-elements-matches.html" . 2)
 ("form-elements-nameditem-01.html" . 3)
 ("form-elements-nameditem-02.html" . 1) ("form-elements-sameobject.html" . 1)
 ("form-indexed-element-shadow.html" . 1) ("form-indexed-element.html" . 2)
 ("form-length.html" . 1) ("form-nameditem.html" . 17)
 ("form-requestsubmit.html" . 10) ("form-validation-checkValidity.html" . 130)
 ("form-validation-reportValidity.html" . 130)
 ("form-validation-validate.html" . 8)
 ("form-validation-validity-badInput.html" . 11)
 ("form-validation-validity-customError.html" . 8)
 ("form-validation-validity-patternMismatch.html" . 85)
 ("form-validation-validity-rangeOverflow-weekmonth.html" . 19)
 ("form-validation-validity-rangeOverflow.html" . 49)
 ("form-validation-validity-rangeUnderflow-weekmonth.html" . 19)
 ("form-validation-validity-rangeUnderflow.html" . 47)
 ("form-validation-validity-stepMismatch.html" . 28)
 ("form-validation-validity-textarea-defaultValue.html" . 5)
 ("form-validation-validity-tooLong.html" . 63)
 ("form-validation-validity-tooShort.html" . 63)
 ("form-validation-validity-typeMismatch.html" . 11)
 ("form-validation-validity-valid-weekmonth.html" . 8)
 ("form-validation-validity-valid.html" . 35)
 ("form-validation-validity-valueMissing-weekmonth.html" . 19)
 ("form-validation-validity-valueMissing.html" . 78)
 ("form-validation-willValidate-datalist.html" . 17)
 ("form-validation-willValidate.html" . 73) ("form.html" . 17)
 ("formAction_document_address.html" . 8) ("form_attribute.html" . 100)
 ("form_owner_and_table.html" . 1) ("form_owner_and_table_2.html" . 1)
 ("form_owner_and_table_3.html" . 1) ("formaction.html" . 8)
 ("input-checkvalidity.html" . 1) ("input-labels.html" . 1)
 ("input-maxlength-emoji.html" . 1)
 ("input-number-validity-dynamic-value-no-change.html" . 1)
 ("input-pattern-dynamic-value.html" . 1) ("input-setcustomvalidity.html" . 1)
 ("input-stepdown-02.html" . 6) ("input-stepdown.html" . 5)
 ("input-stepup.html" . 53) ("input-validationmessage.html" . 1)
 ("input-validity.html" . 1) ("input-valueasdate-invalidstateerr.html" . 1)
 ("input-valueasdate-stepping.html" . 4)
 ("input-valueasdate-typeerror.html" . 4) ("input-valueasdate.html" . 30)
 ("input-valueasnumber-invalidstateerr.html" . 1)
 ("input-valueasnumber-stepping.html" . 7)
 ("input-valueasnumber-typeerror.html" . 4) ("input-valueasnumber.html" . 64)
 ("inputwillvalidate.html" . 2) ("label-attributes.sub.html" . 20)
 ("label-inside-anchor.html" . 1) ("labelable-elements.html" . 26)
 ("meter-leading-plus-sign.html" . 12) ("meter.html" . 50) ("month.html" . 15)
 ("option-element-constructor.html" . 11) ("option-form.html" . 1)
 ("option-index.html" . 4) ("option-label.html" . 12)
 ("option-selected.html" . 3) ("option-text-backslash.html" . 1)
 ("option-text-label.html" . 2) ("option-text-recurse.html" . 11)
 ("option-text-setter.html" . 1) ("option-text-spaces.html" . 50)
 ("option-value.html" . 12) ("progress-2.html" . 4)
 ("progress-max-setting.html" . 1) ("progress.html" . 11)
 ("radio-group-valueMissing.html" . 2) ("radio-valueMissing.html" . 6)
 ("range.html" . 25) ("select-add-optgroup.html" . 1) ("select-add.html" . 2)
 ("select-event.html" . 270) ("select-multiple.html" . 3)
 ("select-named-getter.html" . 4) ("select-remove.html" . 4)
 ("select-restore-invalid-option.html" . 1)
 ("select-selectedOptions-nesting.window.js" . 11)
 ("select-selectedOptions.html" . 8) ("select-validity.html" . 6)
 ("select-value.html" . 4) ("selected-index.html" . 13)
 ("selection-after-content-change.html" . 18)
 ("selection-not-application-textarea.html" . 1)
 ("selection-not-application.html" . 71)
 ("selection-start-end-extra.html" . 11) ("selection-start-end.html" . 1)
 ("selection-value-interactions.html" . 14) ("selection.html" . 42)
 ("setSelectionRange.html" . 1) ("textarea-maxlength.html" . 5)
 ("textarea-minlength.html" . 5) ("textarea-setcustomvalidity.html" . 1)
 ("textarea-textLength.html" . 1) ("textarea-type.html" . 1)
 ("textfieldselection-setRangeText.html" . 88)
 ("textfieldselection-setSelectionRange.html" . 49)
 ("type-change-state-weekmonth.html" . 82) ("type-change-state.html" . 380)
 ("value-defaultValue-textContent.html" . 12) ("valueMode.html" . 40)
 ("wrap-enumerated-ascii-case-insensitive.html" . 1))
