;;; auto-maintained by forms-oracle.lisp — pinned subtest
;;; denominators (file . most-subtests-ever-seen).
(("change-to-empty-value.html" . 1) ("textarea-setcustomvalidity.html" . 1)
 ("wrap-enumerated-ascii-case-insensitive.html" . 1)
 ("textarea-minlength.html" . 5) ("textarea-maxlength.html" . 5)
 ("textarea-type.html" . 1) ("textarea-textLength.html" . 1)
 ("value-defaultValue-textContent.html" . 12)
 ("select-restore-invalid-option.html" . 1) ("select-add-optgroup.html" . 1)
 ("select-validity.html" . 6)
 ("common-HTMLOptionsCollection-namedItem.html" . 6)
 ("common-HTMLOptionsCollection-add.html" . 3)
 ("common-HTMLOptionsCollection.html" . 8) ("select-named-getter.html" . 4)
 ("selected-index.html" . 13) ("select-selectedOptions-nesting.window.js" . 11)
 ("select-selectedOptions.html" . 8) ("select-remove.html" . 4)
 ("select-add.html" . 2) ("select-multiple.html" . 3) ("select-value.html" . 4)
 ("input-validationmessage.html" . 1) ("input-setcustomvalidity.html" . 1)
 ("input-checkvalidity.html" . 1) ("input-validity.html" . 1)
 ("selection.html" . 42) ("input-stepdown-02.html" . 6)
 ("input-stepdown.html" . 5) ("input-stepup.html" . 53)
 ("datetime-local-valueasdate.html" . 1)
 ("input-valueasdate-stepping.html" . 4)
 ("input-valueasdate-invalidstateerr.html" . 1)
 ("input-valueasdate-typeerror.html" . 4) ("input-valueasdate.html" . 30)
 ("input-valueasnumber-invalidstateerr.html" . 1)
 ("input-valueasnumber-typeerror.html" . 4)
 ("input-valueasnumber-stepping.html" . 7) ("input-valueasnumber.html" . 64)
 ("input-labels.html" . 1))
