;;; auto-maintained by forms-oracle.lisp — pinned subtest
;;; denominators (file . most-subtests-ever-seen).
(("HTMLFieldSetElement.html" . 4) ("button-checkvalidity.html" . 1)
 ("button-events.html" . 9) ("button-labels.html" . 1)
 ("button-setcustomvalidity.html" . 1)
 ("button-type-enumerated-ascii-case-insensitive.html" . 2)
 ("button-type.html" . 2) ("button-validation.html" . 6)
 ("button-validationmessage.html" . 1) ("button-validity.html" . 1)
 ("button-willvalidate-readonly-attribute.html" . 1)
 ("button-willvalidate.html" . 1) ("change-to-empty-value.html" . 1)
 ("common-HTMLOptionsCollection-add.html" . 3)
 ("common-HTMLOptionsCollection-namedItem.html" . 6)
 ("common-HTMLOptionsCollection.html" . 8)
 ("datetime-local-valueasdate.html" . 1) ("disabled-001.html" . 5)
 ("disabled-003.html" . 2) ("fieldset-checkvalidity.html" . 1)
 ("fieldset-intrinsic-size.html" . 6) ("fieldset-setcustomvalidity.html" . 1)
 ("fieldset-validationmessage.html" . 1) ("fieldset-validity.html" . 1)
 ("fieldset-willvalidate.html" . 1) ("form.html" . 17)
 ("form_attribute.html" . 100) ("form_owner_and_table.html" . 1)
 ("form_owner_and_table_2.html" . 1) ("form_owner_and_table_3.html" . 1)
 ("input-checkvalidity.html" . 1) ("input-labels.html" . 1)
 ("input-setcustomvalidity.html" . 1) ("input-stepdown-02.html" . 6)
 ("input-stepdown.html" . 5) ("input-stepup.html" . 53)
 ("input-validationmessage.html" . 1) ("input-validity.html" . 1)
 ("input-valueasdate-invalidstateerr.html" . 1)
 ("input-valueasdate-stepping.html" . 4)
 ("input-valueasdate-typeerror.html" . 4) ("input-valueasdate.html" . 30)
 ("input-valueasnumber-invalidstateerr.html" . 1)
 ("input-valueasnumber-stepping.html" . 7)
 ("input-valueasnumber-typeerror.html" . 4) ("input-valueasnumber.html" . 64)
 ("label-attributes.sub.html" . 20) ("label-inside-anchor.html" . 1)
 ("labelable-elements.html" . 26) ("meter-leading-plus-sign.html" . 12)
 ("meter.html" . 50) ("option-element-constructor.html" . 11)
 ("option-form.html" . 1) ("option-index.html" . 4) ("option-label.html" . 12)
 ("option-selected.html" . 3) ("option-text-backslash.html" . 1)
 ("option-text-label.html" . 2) ("option-text-recurse.html" . 11)
 ("option-text-setter.html" . 1) ("option-text-spaces.html" . 50)
 ("option-value.html" . 12) ("progress-2.html" . 4)
 ("progress-max-setting.html" . 1) ("progress.html" . 11)
 ("select-add-optgroup.html" . 1) ("select-add.html" . 2)
 ("select-multiple.html" . 3) ("select-named-getter.html" . 4)
 ("select-remove.html" . 4) ("select-restore-invalid-option.html" . 1)
 ("select-selectedOptions-nesting.window.js" . 11)
 ("select-selectedOptions.html" . 8) ("select-validity.html" . 6)
 ("select-value.html" . 4) ("selected-index.html" . 13) ("selection.html" . 42)
 ("textarea-maxlength.html" . 5) ("textarea-minlength.html" . 5)
 ("textarea-setcustomvalidity.html" . 1) ("textarea-textLength.html" . 1)
 ("textarea-type.html" . 1) ("value-defaultValue-textContent.html" . 12)
 ("wrap-enumerated-ascii-case-insensitive.html" . 1))
