;;;; inspect/html-test.lisp — html5lib tokenizer differential gate.
;;;;
;;;; Each inspect/vectors/html/tokenizer/*.test is an html5lib JSON suite: for
;;;; every test, tokenizing INPUT (in each of its initialStates) must yield the
;;;; expected token stream.  Character tokens are coalesced and ParseError tokens
;;;; ignored (we compare token streams, not error positions).
(defpackage #:weft.html.test (:use #:cl) (:local-nicknames (#:h #:weft.html)) (:export #:run))
(in-package #:weft.html.test)

;;; ---- JSON reader ------------------------------------------------------
(defun json-parse (string)
  (let ((i 0) (n (length string)))
    (labels
        ((peek () (when (< i n) (char string i)))
         (next () (prog1 (char string i) (incf i)))
         (ws () (loop while (and (< i n) (member (char string i) '(#\Space #\Tab #\Newline #\Return))) do (incf i)))
         (value () (ws) (let ((c (peek)))
                          (cond ((char= c #\{) (object)) ((char= c #\[) (array)) ((char= c #\") (jstring))
                                ((or (digit-char-p c) (char= c #\-)) (number))
                                ((char= c #\t) (incf i 4) :true) ((char= c #\f) (incf i 5) :false)
                                ((char= c #\n) (incf i 4) :null))))
         (object () (next) (ws)
           (let ((al '())) (when (char= (peek) #\}) (next) (return-from object '()))
             (loop (ws) (let ((k (jstring))) (ws) (next) (push (cons k (value)) al)) (ws)
                   (if (char= (peek) #\,) (next) (progn (next) (return)))) (nreverse al)))
         (array () (next) (ws)
           (let ((items '())) (when (char= (peek) #\]) (next) (return-from array '()))
             (loop (push (value) items) (ws) (if (char= (peek) #\,) (next) (progn (next) (return)))) (nreverse items)))
         (jstring () (next)
           (with-output-to-string (o)
             (loop for c = (next) until (char= c #\") do
               (if (char= c #\\)
                   (let ((e (next)))
                     (case e (#\n (write-char #\Newline o)) (#\t (write-char #\Tab o)) (#\r (write-char #\Return o))
                       (#\b (write-char #\Backspace o)) (#\f (write-char #\Page o)) (#\/ (write-char #\/ o))
                       (#\\ (write-char #\\ o)) (#\" (write-char #\" o))
                       (#\u (let ((code (parse-integer string :start i :end (+ i 4) :radix 16)))
                              (incf i 4)
                              (if (and (<= #xd800 code #xdbff) (< (+ i 1) n)
                                       (char= (char string i) #\\) (char= (char string (1+ i)) #\u))
                                  (let ((lo (parse-integer string :start (+ i 2) :end (+ i 6) :radix 16)))
                                    (incf i 6)
                                    (write-char (code-char (+ #x10000 (ash (- code #xd800) 10) (- lo #xdc00))) o))
                                  (write-char (code-char code) o))))
                       (t (write-char e o))))
                   (write-char c o)))))
         (number () (let ((s i)) (loop while (and (< i n) (or (digit-char-p (char string i)) (member (char string i) '(#\- #\+ #\. #\e #\E)))) do (incf i))
                      (read-from-string (subseq string s i)))))
      (value))))

(defun slurp (path)
  (with-open-file (s path :external-format :utf-8)
    (let ((str (make-string (file-length s)))) (subseq str 0 (read-sequence str s)))))
(defun field (obj key) (cdr (assoc key obj :test #'string=)))

;;; ---- helpers ----------------------------------------------------------
(defun unescape-double (str)
  "Decode a second layer of \\uXXXX escapes (doubleEscaped tests)."
  (with-output-to-string (o)
    (let ((i 0) (n (length str)))
      (loop while (< i n) do
        (if (and (char= (char str i) #\\) (< (+ i 1) n) (char= (char str (1+ i)) #\u))
            (progn (write-char (code-char (parse-integer str :start (+ i 2) :end (+ i 6) :radix 16)) o) (incf i 6))
            (progn (write-char (char str i) o) (incf i)))))))

(defun state-key (name)
  (cond ((string= name "Data state") :data)
        ((string= name "RCDATA state") :rcdata)
        ((string= name "RAWTEXT state") :rawtext)
        ((string= name "Script data state") :script-data)
        ((string= name "PLAINTEXT state") :plaintext)
        ((string= name "CDATA section state") :data)
        (t :data)))

(defun jnull (x) (if (eq x :null) nil x))
(defun sort-attrs (alist) (sort (mapcar (lambda (p) (cons (car p) (or (cdr p) ""))) alist) #'string< :key #'car))

(defun canon-expected (tok)
  (if (stringp tok) :skip                         ; "ParseError"
      (let ((k (first tok)))
        (cond ((string= k "Character") (list :char (second tok)))
              ((string= k "StartTag") (list :start (second tok) (sort-attrs (third tok)) (eq (fourth tok) :true)))
              ((string= k "EndTag") (list :end (second tok)))
              ((string= k "Comment") (list :comment (second tok)))
              ((string= k "DOCTYPE") (list :doctype (jnull (second tok)) (jnull (third tok)) (jnull (fourth tok)) (eq (fifth tok) :true)))
              (t :skip)))))

(defun canon-ours (tk)
  (ecase (h:tok-type tk)
    (:char (list :char (h:tok-data tk)))
    (:start-tag (list :start (h:tok-name tk) (sort-attrs (h:tok-attrs tk)) (and (h:tok-self-closing tk) t)))
    (:end-tag (list :end (h:tok-name tk)))
    (:comment (list :comment (h:tok-data tk)))
    (:doctype (list :doctype (h:tok-name tk) (h:tok-public tk) (h:tok-system tk) (not (h:tok-force-quirks tk))))
    (:eof :skip)))

(defun coalesce (toks)
  (let ((out '()))
    (dolist (tk toks)
      (if (and (consp tk) (eq (car tk) :char) out (consp (car out)) (eq (caar out) :char))
          (setf (second (car out)) (concatenate 'string (second (car out)) (second tk)))
          (push (copy-tree tk) out)))
    (nreverse out)))

(defun prep (toks) (coalesce (remove :skip toks)))

;;; ---- runner -----------------------------------------------------------
(defun run (&optional only)
  (let* ((dir (asdf:system-relative-pathname "weft" "inspect/vectors/html/tokenizer/"))
         (files (sort (directory (merge-pathnames "*.test" dir)) #'string< :key #'namestring))
         (pass 0) (fail 0) (fails '()))
    (format t "~&=== weft HTML tokenizer gate (html5lib) ===~%")
    (dolist (f files)
      (when (or (null only) (search only (pathname-name f)))
        (let ((fp 0) (ff 0))
          (dolist (test (field (json-parse (slurp f)) "tests"))
            (let* ((dbl (eq (field test "doubleEscaped") :true))
                   (input (let ((s (field test "input"))) (if dbl (unescape-double s) s)))
                   (output (field test "output"))
                   (states (or (field test "initialStates") '("Data state")))
                   (last (field test "lastStartTag"))
                   (want (prep (mapcar (lambda (t0) (let ((c (canon-expected t0)))
                                                      (if (and dbl (consp c))
                                                          (mapcar (lambda (x) (if (stringp x) (unescape-double x) x)) c) c)))
                                       output)))
                   (ok t))
              (handler-case
                  (dolist (st states)
                    (let ((got (prep (mapcar #'canon-ours (h:tokenize input :state (state-key st) :last-start-tag last)))))
                      (unless (equal got want) (setf ok nil))))
                (error () (setf ok nil)))
              (if ok (incf fp)
                  (progn (incf ff) (when (< (length fails) 18)
                                     (push (format nil "[~a] ~s" (pathname-name f) (field test "description")) fails))))))
          (incf pass fp) (incf fail ff)
          (format t "  ~a ~24a ~4d/~d~%" (if (zerop ff) "ok  " "FAIL") (pathname-name f) fp (+ fp ff)))))
    (format t "~%~d passed, ~d failed~%" pass fail)
    (when fails (format t "~%sample failures:~%~{  ~a~%~}" (reverse fails)))
    (values pass fail)))
