;;;; src/script/dom.lisp — the DOM core surface bound onto shuttle host objects.
;;;;
;;;; Node / Element / Document / CharacterData (Text, Comment) / DocumentFragment,
;;;; their traversal accessors, the mutation methods, attribute reflection, and
;;;; the document factory + lookups.  Methods live on shared per-context
;;;; prototypes and recover their backing weft node from `this` via NODE-OF.
(in-package #:weft.script)

;;; ---- node-kind reflection -------------------------------------------------
(defun node-type-of (node)
  (num (case (h:dnode-kind node)
         (:element 1) (:text 3) (:comment 8) (:document 9)
         (:doctype 10) (:fragment 11) (t 1))))

(defvar *html-ns* "http://www.w3.org/1999/xhtml")

(defun element-tag-name (node &optional ctx)
  "tagName/nodeName for an element: uppercased for an HTML-namespace element,
   case-preserved otherwise (XML namespaces are case-sensitive)."
  (let ((info (and ctx (gethash node (context-ns-info ctx)))))
    (cond (info (getf info :qname))
          ((eq (h:dnode-namespace node) :html) (string-upcase (h:dnode-name node)))
          (t (h:dnode-name node)))))

(defun node-name-of (node &optional ctx)
  (case (h:dnode-kind node)
    (:element (element-tag-name node ctx))
    (:text "#text") (:comment "#comment") (:document "#document")
    (:fragment "#document-fragment")
    (:doctype (or (h:dnode-name node) "")) (t "")))

(defun char-data-p (node)
  (member (h:dnode-kind node) '(:text :comment)))

;;; ---- DOMException ---------------------------------------------------------
(defparameter +dom-codes+
  '(("INDEX_SIZE_ERR" . 1) ("DOMSTRING_SIZE_ERR" . 2) ("HIERARCHY_REQUEST_ERR" . 3)
    ("WRONG_DOCUMENT_ERR" . 4) ("INVALID_CHARACTER_ERR" . 5) ("NO_DATA_ALLOWED_ERR" . 6)
    ("NO_MODIFICATION_ALLOWED_ERR" . 7) ("NOT_FOUND_ERR" . 8) ("NOT_SUPPORTED_ERR" . 9)
    ("INUSE_ATTRIBUTE_ERR" . 10) ("INVALID_STATE_ERR" . 11) ("SYNTAX_ERR" . 12)
    ("INVALID_MODIFICATION_ERR" . 13) ("NAMESPACE_ERR" . 14) ("INVALID_ACCESS_ERR" . 15)
    ("VALIDATION_ERR" . 16) ("TYPE_MISMATCH_ERR" . 17) ("SECURITY_ERR" . 18)
    ("NETWORK_ERR" . 19) ("ABORT_ERR" . 20) ("URL_MISMATCH_ERR" . 21)
    ("QUOTA_EXCEEDED_ERR" . 22) ("TIMEOUT_ERR" . 23) ("INVALID_NODE_TYPE_ERR" . 24)
    ("DATA_CLONE_ERR" . 25)))

(defun make-dom-exception (ctx name code message)
  (let ((o (js:make-object :proto (js:eval-script (context-realm ctx) "Error.prototype"))))
    (js:put o "name" name :enumerable nil)
    (js:put o "message" message :enumerable nil)
    (js:put o "code" (num code) :enumerable nil)
    (dolist (p +dom-codes+) (js:put o (car p) (num (cdr p)) :enumerable nil :writable nil))
    o))

(defun throw-dom (ctx name code message)
  (js:js-throw (make-dom-exception ctx name code message)))

(defun ancestor-or-self-p (a node)
  "T if A is NODE or an ancestor of NODE."
  (loop for p = node then (h:dnode-parent p) while p thereis (eq p a)))

(defun name-start-char-p (c)
  (or (alpha-char-p c) (member c '(#\_ #\:))))
(defun valid-name-p (name)
  "A conservative XML Name check: non-empty, a letter/_/: start, and no control
   char, space or markup delimiter (rejects null bytes and digit-led names, per
   Acid3 tests 20/22/23)."
  (and (plusp (length name))
       (name-start-char-p (char name 0))
       (every (lambda (c) (let ((cc (char-code c)))
                            (and (>= cc #x21)
                                 (not (member c '(#\< #\> #\& #\" #\' #\/ #\= #\Space))))))
              name)))

;;; ---- structural mutation (weft side) --------------------------------------
(defun set-text-content (node text)
  "The textContent setter: detach NODE's children and, if TEXT is non-empty,
   give it a single text child holding TEXT (DOM Node.textContent)."
  (if (char-data-p node)
      (setf (h:dnode-data node) text)
      (let ((children (h:dnode-children node)))
        (loop for c across children do (setf (h:dnode-parent c) nil))
        (setf (fill-pointer children) 0)
        (when (plusp (length text))
          (h:dom-append node (h:make-text text))))))

(defun dom-detach (node) (when (h:dnode-parent node) (h:dom-remove node)))

(defun new-node (ctx doc-obj node)
  "Wrap a freshly created NODE, recording its owner document (the document whose
   factory made it) so ownerDocument is correct even while the node is detached."
  (setf (gethash node (context-owner-docs ctx)) (require-node ctx doc-obj))
  (wrap ctx node))

(defun insert-into (parent node ref)
  "Insert NODE (or, if NODE is a fragment, each of its children) into PARENT
   before REF (NIL = append). Returns NODE."
  (if (eq (h:dnode-kind node) :fragment)
      (loop for c across (copy-seq (h:dnode-children node))
            do (h:dom-remove c) (if ref (h:dom-insert-before parent c ref)
                                     (h:dom-append parent c)))
      (progn (dom-detach node)
             (if ref (h:dom-insert-before parent node ref) (h:dom-append parent node))))
  node)

(defun copy-dnode (node deep)
  (let ((c (ecase (h:dnode-kind node)
             (:element (h:make-element (h:dnode-name node)
                                       (copy-alist (h:dnode-attrs node))
                                       (h:dnode-namespace node)))
             (:text (h:make-text (h:dnode-data node)))
             (:comment (h:make-comment (h:dnode-data node)))
             (:fragment (h:make-fragment))
             (:document (h:make-document)))))
    (when (and deep (not (char-data-p node)))
      (loop for ch across (h:dnode-children node)
            do (h:dom-append c (copy-dnode ch t))))
    c))

;;; ---- attributes -----------------------------------------------------------
(defun attr-name (name) (string-downcase (jstr name)))
(defun get-attr (node name) (dom:get-attribute node (attr-name name)))
(defun set-attr (node name value)
  (let* ((n (attr-name name)) (v (jstr value))
         (cell (assoc n (h:dnode-attrs node) :test #'string=)))
    (if cell (setf (cdr cell) v)
        (setf (h:dnode-attrs node)
              (append (h:dnode-attrs node) (list (cons n v)))))))
(defun remove-attr (node name)
  (setf (h:dnode-attrs node)
        (remove (attr-name name) (h:dnode-attrs node) :key #'car :test #'string=)))

;;; ---- live collections -----------------------------------------------------
(defun index-string-p (k)
  (and (stringp k) (plusp (length k)) (every #'digit-char-p k)))

(defun make-collection (ctx list-fn &optional name-fn)
  "A live NodeList/HTMLCollection: length + integer indexing + item(), reading
   LIST-FN (-> a fresh CL list of weft nodes) on every access. If NAME-FN is
   given, an unknown string key is looked up by name (namedItem semantics)."
  (let* ((realm (context-realm ctx))
         (item (js:native-function realm "item"
                 (lambda (this a) (declare (ignore this))
                   (let ((i (int-arg a 0)) (l (funcall list-fn)))
                     (if (< -1 i (length l)) (wrap ctx (nth i l)) js:*null*)))
                 1))
         (named (js:native-function realm "namedItem"
                  (lambda (this a) (declare (ignore this))
                    (let ((node (and name-fn (funcall name-fn (jstr (arg a 0))))))
                      (if node (wrap ctx node) js:*null*)))
                  1)))
    (js:make-host-object realm
      :get (lambda (o key rcv) (declare (ignore rcv))
             (let ((key (js:to-property-key key)))   ; obj[0] arrives as a number
               (cond
                 ((and (stringp key) (string= key "length"))
                  (num (length (funcall list-fn))))
                 ((index-string-p key)
                  (let ((i (parse-integer key)) (l (funcall list-fn)))
                    (if (< i (length l)) (wrap ctx (nth i l)) js:*undefined*)))
                 ((and (stringp key) (string= key "item")) item)
                 ((and (stringp key) (string= key "namedItem")) named)
                 ((and name-fn (stringp key) (funcall name-fn key))
                  (wrap ctx (funcall name-fn key)))
                 (t (js:js-get (js:js-object-proto o) key o))))))))

(defparameter +form-control-tags+
  '("input" "button" "select" "textarea" "fieldset" "object" "output"))

(defun form-controls (form)
  (remove-if-not (lambda (n) (member (h:dnode-name n) +form-control-tags+ :test #'string=))
                 (dom:get-elements-by-tag-name form "*")))

(defun named-control (form name)
  (find-if (lambda (n) (or (equal (dom:get-attribute n "name") name)
                           (equal (dom:get-attribute n "id") name)))
           (form-controls form)))

(defun children-list (node)
  (coerce (h:dnode-children node) 'list))
(defun element-children-list (node)
  (loop for c across (h:dnode-children node)
        when (eq (h:dnode-kind c) :element) collect c))

;;; ---------------------------------------------------------------------------
;;; Node.prototype
;;; ---------------------------------------------------------------------------
(defun install-node-proto (ctx np)
  (macrolet ((n (this) `(require-node ctx ,this)))
    (defget ctx np "nodeType" (this) (node-type-of (n this)))
    (defget ctx np "nodeName" (this) (node-name-of (n this) ctx))
    (defget ctx np "parentNode" (this) (wrap ctx (h:dnode-parent (n this))))
    (defget ctx np "parentElement" (this)
      (let ((p (h:dnode-parent (n this))))
        (wrap ctx (and p (eq (h:dnode-kind p) :element) p))))
    (defget ctx np "ownerDocument" (this)
      (let ((node (n this)))
        (cond ((eq (h:dnode-kind node) :document) js:*null*)
              ((gethash node (context-owner-docs ctx)) (wrap ctx (gethash node (context-owner-docs ctx))))
              (t (loop for p = (h:dnode-parent node) then (h:dnode-parent p)
                       while p when (eq (h:dnode-kind p) :document) return (wrap ctx p)
                       finally (return js:*null*))))))
    (defget ctx np "firstChild" (this)
      (let ((ch (h:dnode-children (n this))))
        (if (plusp (length ch)) (wrap ctx (aref ch 0)) js:*null*)))
    (defget ctx np "lastChild" (this) (wrap ctx (h:dom-last-child (n this))))
    (defget ctx np "nextSibling" (this)
      (let* ((node (n this)) (p (h:dnode-parent node)))
        (if p (let* ((ch (h:dnode-children p)) (i (position node ch)))
                (if (and i (< (1+ i) (length ch))) (wrap ctx (aref ch (1+ i))) js:*null*))
            js:*null*)))
    (defget ctx np "previousSibling" (this)
      (let* ((node (n this)) (p (h:dnode-parent node)))
        (wrap ctx (and p (h:dom-prev-sibling p node)))))
    (defget ctx np "childNodes" (this)
      (let ((node (n this))) (make-collection ctx (lambda () (children-list node)))))
    (defgetset ctx np "nodeValue" (this)
      (if (char-data-p (n this)) (h:dnode-data (n this)) js:*null*)
      (v) (when (char-data-p (n this))
            (setf (h:dnode-data (n this)) (jstr v)) (setf (context-dirty ctx) t)))
    (defgetset ctx np "textContent" (this)
      (if (eq (h:dnode-kind (n this)) :document) js:*null* (dom:text-content (n this)))
      (v) (progn (set-text-content (n this) (jstr v)) (setf (context-dirty ctx) t)))

    (defmethod* ctx np "hasChildNodes" 0 (this a)
      (jbool (plusp (length (h:dnode-children (n this))))))
    (defmethod* ctx np "appendChild" 1 (this a)
      (let ((parent (n this)) (child (require-node ctx (arg a 0))))
        (when (ancestor-or-self-p child parent)
          (throw-dom ctx "HierarchyRequestError" 3 "would create a cycle"))
        (insert-into parent child nil) (setf (context-dirty ctx) t) (arg a 0)))
    (defmethod* ctx np "insertBefore" 2 (this a)
      (let* ((parent (n this)) (new (require-node ctx (arg a 0)))
             (ref-obj (arg a 1))
             (ref (and (not (nullish ref-obj)) (require-node ctx ref-obj))))
        (when (ancestor-or-self-p new parent)
          (throw-dom ctx "HierarchyRequestError" 3 "would create a cycle"))
        (when (and ref (not (eq (h:dnode-parent ref) parent)))
          (throw-dom ctx "NotFoundError" 8 "reference node is not a child"))
        (insert-into parent new ref) (setf (context-dirty ctx) t) (arg a 0)))
    (defmethod* ctx np "removeChild" 1 (this a)
      (let ((parent (n this)) (child (require-node ctx (arg a 0))))
        (unless (eq (h:dnode-parent child) parent)
          (throw-dom ctx "NotFoundError" 8 "node is not a child"))
        (h:dom-remove child) (setf (context-dirty ctx) t) (arg a 0)))
    (defmethod* ctx np "replaceChild" 2 (this a)
      (let ((parent (n this)) (new (require-node ctx (arg a 0)))
            (old (require-node ctx (arg a 1))))
        (unless (eq (h:dnode-parent old) parent)
          (throw-dom ctx "NotFoundError" 8 "node is not a child"))
        (when (ancestor-or-self-p new parent)
          (throw-dom ctx "HierarchyRequestError" 3 "would create a cycle"))
        (insert-into parent new old) (h:dom-remove old)
        (setf (context-dirty ctx) t) (arg a 1)))
    (defmethod* ctx np "cloneNode" 1 (this a)
      (wrap ctx (copy-dnode (n this) (truthy (arg a 0)))))
    (defmethod* ctx np "contains" 1 (this a)
      (let ((node (n this)) (other (node-of ctx (arg a 0))))
        (jbool (and other (loop for p = other then (h:dnode-parent p)
                                while p thereis (eq p node))))))
    ;; Node type constants (also mirrored on the constructor in Acid tests).
    (dolist (pair '(("ELEMENT_NODE" . 1) ("ATTRIBUTE_NODE" . 2) ("TEXT_NODE" . 3)
                    ("CDATA_SECTION_NODE" . 4) ("ENTITY_REFERENCE_NODE" . 5)
                    ("ENTITY_NODE" . 6) ("PROCESSING_INSTRUCTION_NODE" . 7)
                    ("COMMENT_NODE" . 8) ("DOCUMENT_NODE" . 9) ("DOCUMENT_TYPE_NODE" . 10)
                    ("DOCUMENT_FRAGMENT_NODE" . 11) ("NOTATION_NODE" . 12)))
      (js:put np (car pair) (num (cdr pair)) :enumerable nil :writable nil :configurable nil))))

;;; ---------------------------------------------------------------------------
;;; Element.prototype (<- Node.prototype)
;;; ---------------------------------------------------------------------------
(defun install-element-proto (ctx ep)
  (macrolet ((n (this) `(require-node ctx ,this)))
    (defget ctx ep "tagName" (this) (element-tag-name (n this) ctx))
    (defget ctx ep "localName" (this)
      (let ((info (gethash (n this) (context-ns-info ctx))))
        (if info (getf info :local) (h:dnode-name (n this)))))
    (defget ctx ep "prefix" (this)
      (let ((info (gethash (n this) (context-ns-info ctx))))
        (if (and info (getf info :prefix)) (getf info :prefix) js:*null*)))
    (defget ctx ep "namespaceURI" (this)
      (let ((info (gethash (n this) (context-ns-info ctx))))
        (cond (info (or (getf info :ns) js:*null*))
              ((eq (h:dnode-namespace (n this)) :html) *html-ns*)
              (t js:*null*))))
    (defgetset ctx ep "id" (this) (or (get-attr (n this) "id") "")
      (v) (progn (set-attr (n this) "id" v) (setf (context-dirty ctx) t)))
    (defgetset ctx ep "className" (this) (or (get-attr (n this) "class") "")
      (v) (progn (set-attr (n this) "class" v) (setf (context-dirty ctx) t)))
    ;; Reflected IDL attributes whose property name differs from the content
    ;; attribute (DOM2 HTML): htmlFor<->for, httpEquiv<->http-equiv.
    (defgetset ctx ep "name" (this) (or (get-attr (n this) "name") "")
      (v) (progn (set-attr (n this) "name" (jstr v)) (setf (context-dirty ctx) t)))
    (defgetset ctx ep "title" (this) (or (get-attr (n this) "title") "")
      (v) (progn (set-attr (n this) "title" (jstr v)) (setf (context-dirty ctx) t)))
    (defgetset ctx ep "dir" (this) (or (get-attr (n this) "dir") "")
      (v) (progn (set-attr (n this) "dir" (jstr v)) (setf (context-dirty ctx) t)))
    (defgetset ctx ep "lang" (this) (or (get-attr (n this) "lang") "")
      (v) (progn (set-attr (n this) "lang" (jstr v)) (setf (context-dirty ctx) t)))
    (defgetset ctx ep "htmlFor" (this) (or (get-attr (n this) "for") "")
      (v) (progn (set-attr (n this) "for" (jstr v)) (setf (context-dirty ctx) t)))
    (defgetset ctx ep "httpEquiv" (this) (or (get-attr (n this) "http-equiv") "")
      (v) (progn (set-attr (n this) "http-equiv" (jstr v)) (setf (context-dirty ctx) t)))
    (defget ctx ep "children" (this)
      (let ((node (n this))) (make-collection ctx (lambda () (element-children-list node)))))
    (defget ctx ep "firstElementChild" (this) (wrap ctx (dom:first-element-child (n this))))
    (defget ctx ep "lastElementChild" (this) (wrap ctx (dom:last-element-child (n this))))
    (defget ctx ep "nextElementSibling" (this) (wrap ctx (dom:next-element-sibling (n this))))
    (defget ctx ep "previousElementSibling" (this) (wrap ctx (dom:previous-element-sibling (n this))))
    (defget ctx ep "childElementCount" (this) (num (dom:child-element-count (n this))))
    (defget ctx ep "style" (this) (element-style-object ctx (n this)))
    ;; HTMLFormElement.elements / .length (live, with named access).
    (defget ctx ep "elements" (this)
      (let ((node (n this)))
        (if (string= (h:dnode-name node) "form")
            (make-collection ctx (lambda () (form-controls node))
                             (lambda (name) (named-control node name)))
            js:*undefined*)))
    (defget ctx ep "length" (this)
      (let ((node (n this)))
        (if (string= (h:dnode-name node) "form")
            (num (length (form-controls node))) js:*undefined*)))
    ;; iframe/object contentDocument: hand back a fresh, empty document the test
    ;; can build into (Acid3's getTestDocument path).
    (defget ctx ep "contentDocument" (this) (content-document ctx (n this)))
    (defget ctx ep "contentWindow" (this) (proto ctx :window))

    (defmethod* ctx ep "getAttribute" 1 (this a)
      (opt (get-attr (n this) (jstr (arg a 0)))))
    (defmethod* ctx ep "setAttribute" 2 (this a)
      (set-attr (n this) (jstr (arg a 0)) (arg a 1))
      (setf (context-dirty ctx) t) js:*undefined*)
    (defmethod* ctx ep "removeAttribute" 1 (this a)
      (remove-attr (n this) (jstr (arg a 0)))
      (setf (context-dirty ctx) t) js:*undefined*)
    (defmethod* ctx ep "hasAttribute" 1 (this a)
      (jbool (dom:has-attribute (n this) (attr-name (arg a 0)))))
    (defmethod* ctx ep "hasAttributes" 0 (this a)
      (jbool (and (h:dnode-attrs (n this)) t)))
    (defmethod* ctx ep "getElementsByTagName" 1 (this a)
      (let ((node (n this)) (tag (string-downcase (jstr (arg a 0)))))
        (make-collection ctx (lambda ()
                               ;; getElementsByTagName excludes the context node itself
                               (remove node (dom:get-elements-by-tag-name node tag))))))
    (defmethod* ctx ep "getElementsByClassName" 1 (this a)
      (let ((node (n this)) (cls (jstr (arg a 0))))
        (make-collection ctx (lambda () (dom:get-elements-by-class-name node cls)))))
    (defmethod* ctx ep "matches" 1 (this a)
      (jbool (ignore-errors (css:selector-matches-p
                             (first (css:parse-selector-list (jstr (arg a 0)))) (n this)))))
    ;; HTMLElement.click(): dispatch a synthetic bubbling, cancelable click event.
    (defmethod* ctx ep "click" 0 (this a)
      (let* ((ev (make-event-object ctx "click" nil)) (e (evt-of ctx ev)))
        (setf (evt-bubbles e) t (evt-cancelable e) t)
        (dispatch-event ctx (n this) ev))
      js:*undefined*)
    ;; type/value reflections for form controls.
    (defgetset ctx ep "type" (this)
      (let* ((node (n this)) (tag (h:dnode-name node)) (raw (get-attr node "type")))
        (cond ((string= tag "button")
               (let ((v (and raw (string-downcase raw))))
                 (if (member v '("submit" "reset" "button" "menu") :test #'equal) v "submit")))
              ((string= tag "input")
               (let ((v (and raw (string-downcase raw))))
                 (if (member v '("text" "password" "checkbox" "radio" "submit" "reset"
                                 "button" "hidden" "image" "file" "color" "date" "email"
                                 "number" "range" "search" "tel" "time" "url" "month"
                                 "week" "datetime-local") :test #'equal)
                     v "text")))
              (t (or raw ""))))
      (v) (progn (set-attr (n this) "type" (jstr v)) (setf (context-dirty ctx) t)))
    (defgetset ctx ep "value" (this)
      (let ((node (n this)))
        (if (string= (h:dnode-name node) "input")
            (multiple-value-bind (v present) (gethash node (context-input-values ctx))
              (if present v (or (get-attr node "value") "")))
            (or (get-attr node "value") "")))
      (v) (let ((node (n this)))
            (if (string= (h:dnode-name node) "input")
                (setf (gethash node (context-input-values ctx)) (jstr v))
                (progn (set-attr node "value" (jstr v)) (setf (context-dirty ctx) t)))))))

;;; ---------------------------------------------------------------------------
;;; CharacterData (Text, Comment)  (<- Node.prototype)
;;; ---------------------------------------------------------------------------
(defun install-chardata-proto (ctx cp)
  (macrolet ((n (this) `(require-node ctx ,this)))
    (defgetset ctx cp "data" (this) (or (h:dnode-data (n this)) "")
      (v) (progn (setf (h:dnode-data (n this)) (jstr v)) (setf (context-dirty ctx) t)))
    (defget ctx cp "length" (this) (num (length (or (h:dnode-data (n this)) ""))))
    (defmethod* ctx cp "appendData" 1 (this a)
      (setf (h:dnode-data (n this)) (concatenate 'string (or (h:dnode-data (n this)) "") (jstr (arg a 0))))
      (setf (context-dirty ctx) t) js:*undefined*)
    (defmethod* ctx cp "substringData" 2 (this a)
      (let* ((s (or (h:dnode-data (n this)) "")) (off (int-arg a 0))
             (cnt (int-arg a 1)))
        (subseq s (min off (length s)) (min (length s) (+ off cnt)))))))

;;; ---------------------------------------------------------------------------
;;; Document.prototype (<- Node.prototype)
;;; ---------------------------------------------------------------------------
(defun install-document-proto (ctx dp)
  (macrolet ((n (this) `(require-node ctx ,this)))
    (defget ctx dp "documentElement" (this)
      (wrap ctx (dom:first-element-child (n this))))
    (defget ctx dp "body" (this) (wrap ctx (find-tag (n this) "body")))
    (defget ctx dp "head" (this) (wrap ctx (find-tag (n this) "head")))
    (defget ctx dp "forms" (this)
      (let ((node (n this))) (make-collection ctx (lambda () (dom:get-elements-by-tag-name node "form")))))
    (defget ctx dp "defaultView" (this) (proto ctx :window))
    (defgetset ctx dp "title" (this)
      (let ((tn (find-tag (n this) "title"))) (if tn (dom:text-content tn) ""))
      (v) (let* ((doc (n this)) (tn (find-tag doc "title")))
            (when tn (set-text-content tn (jstr v)) (setf (context-dirty ctx) t))))
    (defmethod* ctx dp "getElementById" 1 (this a)
      (wrap ctx (dom:get-element-by-id (n this) (jstr (arg a 0)))))
    (defmethod* ctx dp "getElementsByTagName" 1 (this a)
      (let ((node (n this)) (tag (string-downcase (jstr (arg a 0)))))
        (make-collection ctx (lambda () (remove node (dom:get-elements-by-tag-name node tag))))))
    (defmethod* ctx dp "getElementsByClassName" 1 (this a)
      (let ((node (n this)) (cls (jstr (arg a 0))))
        (make-collection ctx (lambda () (dom:get-elements-by-class-name node cls)))))
    (defmethod* ctx dp "createElement" 1 (this a)
      (let ((name (jstr (arg a 0))))
        (unless (valid-name-p name)
          (throw-dom ctx "InvalidCharacterError" 5 "invalid element name"))
        (new-node ctx this (h:make-element (string-downcase name)))))
    (defmethod* ctx dp "createElementNS" 2 (this a)
      (let* ((nsv (arg a 0)) (ns (if (nullish nsv) nil (jstr nsv))) (name (jstr (arg a 1)))
             (colon (position #\: name)))
        (unless (and (plusp (length name))
                     (name-start-char-p (char name (if colon (1+ colon) 0)))
                     (every (lambda (c) (and (>= (char-code c) #x21)
                                             (not (member c '(#\< #\> #\& #\" #\' #\/ #\=)))))
                            name))
          (throw-dom ctx "InvalidCharacterError" 5 "invalid element name"))
        ;; DOM "validate and extract" namespace rules.
        (let ((prefix (and colon (subseq name 0 colon))))
          (when (or (and colon (or (zerop colon) (= colon (1- (length name)))
                                   (position #\: name :start (1+ colon))))
                    (and prefix (null ns))
                    (and (equal prefix "xml") (not (equal ns "http://www.w3.org/XML/1998/namespace")))
                    (and (or (equal name "xmlns") (equal prefix "xmlns"))
                         (not (equal ns "http://www.w3.org/2000/xmlns/")))
                    (and (equal ns "http://www.w3.org/2000/xmlns/")
                         (not (or (equal name "xmlns") (equal prefix "xmlns")))))
            (throw-dom ctx "NamespaceError" 14 "malformed or invalid qualified name")))
        ;; A namespaced element keeps the given case (XML is case-sensitive); only
        ;; the HTML parser lowercases.  Record ns/prefix/localName for reflection.
        (let ((el (h:make-element name nil
                                  (cond ((and ns (search "svg" ns)) :svg)
                                        ((and ns (search "MathML" ns)) :math) (t :html)))))
          (setf (gethash el (context-ns-info ctx))
                (list :ns ns :qname name
                      :prefix (and colon (subseq name 0 colon))
                      :local (if colon (subseq name (1+ colon)) name)))
          (new-node ctx this el))))
    (defmethod* ctx dp "createTextNode" 1 (this a) (new-node ctx this (h:make-text (jstr (arg a 0))))) 
    (defmethod* ctx dp "createComment" 1 (this a) (new-node ctx this (h:make-comment (jstr (arg a 0))))) 
    (defmethod* ctx dp "createDocumentFragment" 0 (this a) (new-node ctx this (h:make-fragment)))
    (defmethod* ctx dp "createEvent" 1 (this a) (make-event-object ctx "" nil))
    (defmethod* ctx dp "write" 1 (this a)
      (dom-write ctx (apply #'concatenate 'string (mapcar #'jstr a))) js:*undefined*)
    (defmethod* ctx dp "writeln" 1 (this a)
      (dom-write ctx (concatenate 'string (apply #'concatenate 'string (mapcar #'jstr a)) (string #\Newline)))
      js:*undefined*)
    (defmethod* ctx dp "open" 0 (this a) (js:js-get (proto ctx :window) "document"))
    (defmethod* ctx dp "close" 0 (this a) js:*undefined*)
    (defget ctx dp "implementation" (this) (dom-implementation ctx))))

(defun valid-qname-p (qname)
  "A qualified name: an optional single prefix and a local part, each a valid
   Name, with the colon neither leading nor trailing."
  (let ((colon (position #\: qname)))
    (and (plusp (length qname))
         (or (null (position #\: qname :start (1+ (or colon -1))))  ; at most one colon
             (null colon))
         (if colon
             (and (plusp colon) (< (1+ colon) (length qname))
                  (name-start-char-p (char qname 0))
                  (name-start-char-p (char qname (1+ colon))))
             (name-start-char-p (char qname 0))))))

(defun dom-implementation (ctx)
  "The shared DOMImplementation object for this context."
  (or (proto ctx :implementation)
      (let ((impl (js:make-object :proto (js:eval-script (context-realm ctx) "Object.prototype"))))
        (setf (proto ctx :implementation) impl)
        (defmethod* ctx impl "hasFeature" 2 (this a) js:*true*)
        (defmethod* ctx impl "createDocument" 3 (this a)
          (let ((d (h:make-document)) (qn (arg a 1)))
            (unless (nullish qn)
              (unless (valid-qname-p (jstr qn))
                (throw-dom ctx "InvalidCharacterError" 5 "invalid qualified name"))
              (h:dom-append d (h:make-element (jstr qn))))
            (wrap ctx d)))
        (defmethod* ctx impl "createHTMLDocument" 1 (this a)
          (let* ((d (h:make-document)) (html (h:make-element "html"))
                 (head (h:make-element "head")) (title (h:make-element "title"))
                 (body (h:make-element "body")))
            (h:dom-append d html) (h:dom-append html head)
            (h:dom-append head title) (h:dom-append html body)
            (unless (js:js-undefined-p (arg a 0))
              (h:dom-append title (h:make-text (jstr (arg a 0)))))
            (wrap ctx d)))
        (defmethod* ctx impl "createDocumentType" 3 (this a)
          (let ((qname (jstr (arg a 0))))
            (unless (every (lambda (c) (>= (char-code c) #x21)) qname)
              (throw-dom ctx "InvalidCharacterError" 5 "invalid doctype name"))
            (unless (valid-qname-p qname)
              (throw-dom ctx "NamespaceError" 14 "malformed qualified name"))
            (wrap ctx (h:make-element qname))))   ; a stand-in DocumentType node
        impl)))

(defun dom-write (ctx str)
  "document.write: parse STR as an HTML fragment and splice its body-level nodes
   into the DOM right after the currently-executing <script> (or at end of body)."
  (let* ((frag (h:parse-html str))
         (body (find-tag frag "body"))
         (nodes (and body (coerce (h:dnode-children body) 'list)))
         (script (context-current-script ctx)))
    (if (and script (h:dnode-parent script))
        (let* ((parent (h:dnode-parent script)) (ch (h:dnode-children parent))
               (i (position script ch))
               (ref (and i (< (1+ i) (length ch)) (aref ch (1+ i)))))
          (dolist (nd nodes)
            (h:dom-remove nd)
            (if ref (h:dom-insert-before parent nd ref) (h:dom-append parent nd))))
        (let ((b (find-tag (context-document ctx) "body")))
          (when b (dolist (nd nodes) (h:dom-remove nd) (h:dom-append b nd)))))
    (setf (context-dirty ctx) t)))

(defun find-tag (root tag)
  (first (dom:get-elements-by-tag-name root tag)))

(defun content-document (ctx element)
  "Lazily give an <iframe>/<object> a fresh, empty child document (memoized on
   the element) so a script can populate it (Acid3's getTestDocument)."
  (if (member (h:dnode-name element) '("iframe" "object" "frame") :test #'string=)
      (let ((doc (or (gethash element (context-iframe-docs ctx))
                     (let ((d (h:make-document)))
                       (h:dom-append d (h:make-element "html"))
                       (setf (gethash element (context-iframe-docs ctx)) d)
                       d))))
        (wrap ctx doc))
      js:*null*))
