;;;; forms-select.lisp — HTMLElement IDL surface for <select> (WPT swarm unit).
;;;; Self-registering into the element-proto hook (see core.lisp).  The installer
;;;; runs on the shared element prototype; each accessor must gate on the node's
;;;; tag ((string= (h:dnode-name (n this)) "select")) so it only acts on <select>.
(in-package #:weft.script)

(defun install-forms-select (ctx ep)
  (declare (ignorable ctx ep))
  (macrolet ((n (this) `(require-node ctx ,this))
             (tag-gate (this) `(string= (h:dnode-name (n ,this)) "select")))
    (let ((selected-options-cache (make-hash-table :test 'eq))
          (explicitly-deselected (make-hash-table :test 'eq)))
      (labels
          ((select-options-list (node)
             (dom:get-elements-by-tag-name node "option"))
           (select-child-text (node)
             (let ((out ""))
               (loop for c across (h:dnode-children node)
                     when (eq (h:dnode-kind c) :text)
                     do (setq out (concatenate 'string out (h:dnode-data c))))
               out))
           (select-option-value (node)
             (or (get-attr node "value") (select-child-text node)))
           (select-first-non-disabled (opts)
             (position-if (lambda (o) (not (dom:has-attribute o "disabled"))) opts))
           (select-first-selected (node)
             (let* ((opts (select-options-list node))
                    (sel (position-if (lambda (o) (dom:has-attribute o "selected")) opts)))
               (if sel (nth sel opts)
                   (and (not (dom:has-attribute node "multiple"))
                        (let ((fnd (select-first-non-disabled opts)))
                          (when fnd (nth fnd opts)))))))
           (select-selected-index (node)
             (let* ((opts (select-options-list node))
                    (sel (position-if (lambda (o) (dom:has-attribute o "selected")) opts)))
               (if sel sel
                   (if (not (dom:has-attribute node "multiple"))
                       (or (select-first-non-disabled opts) -1)
                       -1))))
           (select-set-selected (node idx)
             (let ((opts (select-options-list node)))
               (when (and (>= idx 0) (< idx (length opts)))
                 (let ((opt (nth idx opts)))
                   (dolist (o opts)
                     (unless (eq o opt) (remove-attr o "selected")))
                   (set-attr opt "selected" "")
                   (setf (context-dirty ctx) t))
                 t)))
           (select-set-selected-safe (node idx)
             (if (and (>= idx 0) (< idx (length (select-options-list node))))
                 (select-set-selected node idx)
                 (progn
                   (dolist (o (select-options-list node)) (remove-attr o "selected"))
                   (setf (context-dirty ctx) t))))
           (select-add-option (node element before)
             (dom-detach element)
             (if (nullish before)
                 (h:dom-append node element)
                 (let* ((opts (select-options-list node))
                        (ref-node (and (numberp before)
                                       (>= before 0) (< before (length opts))
                                       (nth before opts))))
                   (if ref-node
                       (h:dom-insert-before (h:dnode-parent ref-node) element ref-node)
                       (h:dom-append node element))))
             (setf (context-dirty ctx) t))
           (select-remove-option (node idx)
             (let ((opts (select-options-list node)))
               (when (and (>= idx 0) (< idx (length opts)))
                 (h:dom-remove (nth idx opts))
                 (setf (context-dirty ctx) t))))
           (select-trim-options (node new-len)
             (let* ((opts (select-options-list node))
                    (cur (length opts)))
               (when (< new-len cur)
                 (loop for i from (1- cur) downto new-len
                       do (h:dom-remove (nth i opts)))
                 (setf (context-dirty ctx) t))))
           (select-extend-options (node new-len)
             (let ((cur (length (select-options-list node))))
               (when (> new-len cur)
                 (loop repeat (- new-len cur)
                       do (let ((new-opt (h:make-element "option")))
                            (h:dom-append node new-opt)))
                 (setf (context-dirty ctx) t))))
           (select-set-options-length (node new-val)
             (let* ((new-len (max 0 (floor (js:to-number new-val))))
                    (cur (length (select-options-list node))))
               (cond ((< new-len cur) (select-trim-options node new-len))
                     ((> new-len cur) (select-extend-options node new-len)))))
           (select-options-index-set (node idx val)
             (let ((opts (select-options-list node)))
               (when (< idx (length opts))
                 (if (nullish val)
                     (progn (h:dom-remove (nth idx opts))
                            (setf (context-dirty ctx) t))
                     (let ((el (require-node ctx val)))
                       (unless (eq el (nth idx opts))
                         (dom-detach el)
                         (h:dom-insert-before node el (nth idx opts))
                         (h:dom-remove (nth idx opts))
                         (setf (context-dirty ctx) t)))))))
           (select-options-named-item (node name)
             (let* ((opts (select-options-list node))
                    (found (find name opts :test #'string=
                                 :key (lambda (o) (or (get-attr o "id") (get-attr o "name") "")))))
               (if found (wrap ctx found) js:*null*)))
           (select-make-options-collection (node)
             (let* ((realm (context-realm ctx))
                    (htmlcol-proto (proto ctx :htmlcollection))
                    (obj (js:make-host-object realm
                          :proto htmlcol-proto
                          :get (lambda (o key rcv) (declare (ignore rcv))
                            (let ((key (js:to-property-key key)))
                              (cond
                                ((and (stringp key) (string= key "length"))
                                 (num (length (select-options-list node))))
                                ((and (stringp key) (string= key "selectedIndex"))
                                 (num (select-selected-index node)))
                                ((and (stringp key) (string= key "add"))
                                 (js:native-function realm "add"
                                   (lambda (this a) (declare (ignore this))
                                     (let* ((el (require-node ctx (arg a 0)))
                                            (before (arg a 1))
                                            (b (if (or (nullish before) (js:js-undefined-p before))
                                                   nil
                                                   (let ((n (ignore-errors (floor (js:to-number before)))))
                                                     (if (and n (numberp n)) n (require-node ctx before))))))
                                       (select-add-option node el b)
                                       js:*undefined*))
                                   2))
                                ((and (stringp key) (string= key "remove"))
                                 (js:native-function realm "remove"
                                   (lambda (this a) (declare (ignore this))
                                     (let* ((idx (arg a 0))
                                            (n (if (js:js-undefined-p idx) -1
                                                   (floor (js:to-number idx)))))
                                       (select-remove-option node n))
                                     js:*undefined*)
                                   1))
                                ((and (stringp key) (string= key "item"))
                                 (js:native-function realm "item"
                                   (lambda (this a) (declare (ignore this))
                                     (let ((i (int-arg a 0)) (l (select-options-list node)))
                                       (if (< -1 i (length l)) (wrap ctx (nth i l)) js:*null*)))
                                   1))
                                ((and (stringp key) (string= key "namedItem"))
                                 (js:native-function realm "namedItem"
                                   (lambda (this a) (declare (ignore this))
                                     (select-options-named-item node (jstr (arg a 0))))
                                   1))
                                ((index-string-p key)
                                 (let ((i (parse-integer key)) (l (select-options-list node)))
                                   (if (< i (length l)) (wrap ctx (nth i l)) js:*undefined*)))
                                ((and (stringp key) (plusp (length key))
                                      (let ((found (select-options-named-item node key)))
                                        (and (not (eq found js:*null*)) found)))
                                 (select-options-named-item node key))
                                (t (js:js-get (js:js-object-proto o) key o)))))
                          :has (lambda (o key)
                            (let ((key (js:to-property-key key)))
                              (or (and (stringp key)
                                       (member key '("length" "selectedIndex" "add" "remove"
                                                     "item" "namedItem") :test #'string=))
                                  (and (index-string-p key)
                                       (< (parse-integer key) (length (select-options-list node))))
                                  (and (stringp key) (plusp (length key))
                                       (let ((found (select-options-named-item node key)))
                                         (not (eq found js:*null*))))
                                  (js:js-has (js:js-object-proto o) key))))
                          :set (lambda (o key val rcv) (declare (ignore rcv))
                            (let ((key (js:to-property-key key)))
                              (cond
                                ((and (stringp key) (string= key "length"))
                                 (select-set-options-length node val))
                                ((and (stringp key) (string= key "selectedIndex"))
                                 (select-set-selected-safe node (floor (js:to-number val))))
                                ((index-string-p key)
                                 (select-options-index-set node (parse-integer key) val))
                                (t (js:js-set (js:js-object-proto o) key val o))))
                            t)
                          :own-keys (lambda (o) (declare (ignore o))
                            (append (loop for i from 0 below (length (select-options-list node))
                                          collect (princ-to-string i))
                                    '("length" "selectedIndex" "add" "remove" "item" "namedItem"))))))
               (setf (getf (js::js-object-internal obj) :get-own-property)
                     (lambda (o key) (declare (ignore o))
                       (let ((l (select-options-list node)))
                         (cond
                           ((and (index-string-p key) (< (parse-integer key) (length l)))
                            (js::make-prop :value (wrap ctx (nth (parse-integer key) l))
                                           :enumerable t :configurable t :writable nil))
                           ((and (stringp key) (string= key "length"))
                            (js::make-prop :value (num (length l))
                                           :enumerable t :configurable t :writable t))
                           ((and (stringp key) (string= key "selectedIndex"))
                            (js::make-prop :value (num (select-selected-index node))
                                           :enumerable t :configurable t :writable t))
                           (t nil)))))
               obj)))
        ;; value getter/setter
        (defgetset-for ctx ep "select" "value" (this)
          (let ((node (n this)))
            (if (tag-gate this)
                (let ((sel (select-first-selected node)))
                  (if sel (select-option-value sel) ""))
                js:*undefined*))
          (v) (let ((node (n this)))
                (when (tag-gate this)
                  (let* ((target (jstr v))
                         (opts (select-options-list node))
                         (found (find target opts :test #'string=
                                      :key (lambda (o) (select-option-value o)))))
                    (if found
                        (progn
                          (dolist (o opts) (remove-attr o "selected"))
                          (set-attr found "selected" "")
                          (setf (context-dirty ctx) t))
                        (unless (dom:has-attribute node "multiple")
                          (dolist (o opts) (remove-attr o "selected"))
                          (setf (context-dirty ctx) t)))))))
        ;; type getter
        (defget-for ctx ep "select" "type" (this)
          (let ((node (n this)))
            (if (tag-gate this)
                (if (dom:has-attribute node "multiple") "select-multiple" "select-one")
                js:*undefined*)))
        ;; multiple getter/setter
        (defgetset-for ctx ep "select" "multiple" (this)
          (let ((node (n this)))
            (if (tag-gate this) (jbool (dom:has-attribute node "multiple")) js:*undefined*))
          (v) (let ((node (n this)))
                (when (tag-gate this)
                  (if (js:js-truthy v)
                      (set-attr node "multiple" "")
                      (progn
                        (remove-attr node "multiple")
                        (let* ((opts (select-options-list node))
                               (sel-idx (position-if
                                         (lambda (o) (dom:has-attribute o "selected"))
                                         opts :from-end t)))
                          (when sel-idx
                            (let ((last-sel (nth sel-idx opts)))
                              (dolist (o opts)
                                (unless (eq o last-sel) (remove-attr o "selected"))))))))
                  (setf (context-dirty ctx) t))))
        ;; selectedIndex getter/setter
        (defgetset-for ctx ep "select" "selectedIndex" (this)
          (let ((node (n this)))
            (if (tag-gate this) (num (select-selected-index node)) js:*undefined*))
          (v) (let ((node (n this)))
                (when (tag-gate this)
                  (select-set-selected-safe node (floor (js:to-number v))))))
        ;; length getter/setter
        (defgetset-for ctx ep "select" "length" (this)
          (let ((node (n this)))
            (if (tag-gate this) (num (length (select-options-list node))) js:*undefined*))
          (v) (let ((node (n this)))
                (when (tag-gate this)
                  (select-set-options-length node v))))
        ;; options getter
        (defget-for ctx ep "select" "options" (this)
          (let ((node (n this)))
            (if (tag-gate this) (select-make-options-collection node) js:*undefined*)))
        ;; selectedOptions getter — [SameObject] cached
        (defget-for ctx ep "select" "selectedOptions" (this)
          (let ((node (n this)))
            (if (tag-gate this)
                (let ((obj (gethash node selected-options-cache)))
                  (or obj
                      (setf (gethash node selected-options-cache)
                            (make-collection ctx
                              (lambda ()
                                (remove-if-not (lambda (o) (dom:has-attribute o "selected"))
                                               (select-options-list node)))
                              nil :htmlcollection))))
                js:*undefined*)))
        ;; add method
        (defmethod-for ctx ep "select" "add" 2 (this a)
          (let ((node (n this)))
            (when (tag-gate this)
              (let ((el (require-node ctx (arg a 0)))
                    (before (arg a 1)))
                (select-add-option node el
                  (if (or (nullish before) (js:js-undefined-p before))
                      nil
                      (let ((n (ignore-errors (floor (js:to-number before)))))
                        (if (and n (numberp n)) n (require-node ctx before)))))))
            js:*undefined*))
        ;; remove method — if no args, childNode.remove (remove from parent)
        (defmethod-for ctx ep "select" "remove" 1 (this a)
          (let ((node (n this)))
            (when (tag-gate this)
              (let ((idx (arg a 0)))
                (if (js:js-undefined-p idx)
                    (let ((parent (h:dnode-parent node)))
                      (when parent (h:dom-remove node) (setf (context-dirty ctx) t)))
                    (select-remove-option node (floor (js:to-number idx))))))
            js:*undefined*))
        ;; namedItem method
        (defmethod-for ctx ep "select" "namedItem" 1 (this a)
          (let ((node (n this)))
            (if (tag-gate this)
                (select-options-named-item node (jstr (arg a 0)))
                js:*undefined*)))
        ;; willValidate getter
        (defget-for ctx ep "select" "willValidate" (this)
          (let ((node (n this)))
            (if (tag-gate this) js:*true* js:*undefined*)))
        ;; HTMLOptionElement.selected — IDL property reflecting selectedness
        (defgetset-for ctx ep "option" "selected" (this)
          (let ((node (n this)))
            (if (string= (h:dnode-name node) "option")
                (jbool (or (dom:has-attribute node "selected")
                           (let ((parent (h:dnode-parent node)))
                             (and parent
                                  (string= (h:dnode-name parent) "select")
                                  (not (dom:has-attribute parent "multiple"))
                                  (not (find-if (lambda (o) (dom:has-attribute o "selected"))
                                                (dom:get-elements-by-tag-name parent "option")))
                                  (eq (car (dom:get-elements-by-tag-name parent "option")) node)))))
                js:*undefined*))
          (v) (let ((node (n this)))
                (when (string= (h:dnode-name node) "option")
                  (let ((parent (h:dnode-parent node)))
                    (if (js:js-truthy v)
                        (progn
                          (set-attr node "selected" "")
                          (when (and parent (string= (h:dnode-name parent) "select")
                                     (not (dom:has-attribute parent "multiple")))
                            (dolist (o (dom:get-elements-by-tag-name parent "option"))
                              (unless (eq o node) (remove-attr o "selected")))))
                        (remove-attr node "selected")))
                  (setf (context-dirty ctx) t))))
        ;; checkValidity method
        (defmethod-for ctx ep "select" "checkValidity" 0 (this a)
          (declare (ignore a))
          (let ((node (n this)))
            (if (tag-gate this)
                (if (dom:has-attribute node "required")
                    (let* ((opts (select-options-list node))
                           (sel (find-if (lambda (o) (dom:has-attribute o "selected")) opts)))
                      (if sel
                          (let* ((first (car opts))
                                 (is-placeholder (and first (eq sel first)
                                                      (not (dom:has-attribute node "multiple"))
                                                      (not (get-attr first "value"))
                                                      (string= (select-child-text first) ""))))
                            (jbool (not is-placeholder)))
                          js:*false*))
                    js:*true*)
                js:*undefined*)))))))

(register-element-proto-extension :select #'install-forms-select)