;;;; src/script/tables.lisp — HTML table interfaces.
;;;;
;;;; HTMLTableElement (caption/tHead/tFoot/tBodies/rows + create/delete/insertRow),
;;;; HTMLTableSectionElement (rows/insertRow/deleteRow), and HTMLTableRowElement
;;;; (rowIndex/sectionRowIndex/cells/insertCell/deleteCell).  Installed as
;;;; tag-guarded accessors/methods on the shared Element prototype.
(in-package #:weft.script)

(defun tag= (node name) (and (eq (h:dnode-kind node) :element)
                             (string= (h:dnode-name node) name)))
(defun first-child-tag (parent name)
  (loop for c across (h:dnode-children parent) when (tag= c name) return c))
(defun child-trs (parent)
  (loop for c across (h:dnode-children parent) when (tag= c "tr") collect c))
(defun child-tags (parent name)
  (loop for c across (h:dnode-children parent) when (tag= c name) collect c))

(defun table-rows (table)
  "table.rows: thead rows, then table/tbody rows (tree order), then tfoot rows."
  (let ((heads '()) (bodies '()) (foots '()))
    (loop for c across (h:dnode-children table) do
      (cond ((tag= c "tr") (push c bodies))
            ((tag= c "thead") (dolist (r (child-trs c)) (push r heads)))
            ((tag= c "tbody") (dolist (r (child-trs c)) (push r bodies)))
            ((tag= c "tfoot") (dolist (r (child-trs c)) (push r foots)))))
    (append (nreverse heads) (nreverse bodies) (nreverse foots))))

(defun section-rows (section) (child-trs section))
(defun row-cells (tr)
  (loop for c across (h:dnode-children tr) when (or (tag= c "td") (tag= c "th")) collect c))

(defun insert-child-at (parent node index)
  "Insert NODE as PARENT's INDEX-th child (-1 or >= length => append)."
  (let* ((ch (h:dnode-children parent)) (len (length ch)))
    (dom-detach node)
    (if (or (< index 0) (>= index len)) (h:dom-append parent node)
        (h:dom-insert-before parent node (aref ch index)))
    node))

(defun install-table-interfaces (ctx ep)
  (macrolet ((n (this) `(require-node ctx ,this))
             (when-tag (this name &body body)
               `(let ((node (n ,this))) (if (tag= node ,name) (progn ,@body) js:*undefined*))))
    ;; ---- HTMLTableElement ----
    (defget ctx ep "caption" (this) (when-tag this "table" (wrap ctx (first-child-tag node "caption"))))
    (defget ctx ep "tHead" (this) (when-tag this "table" (wrap ctx (first-child-tag node "thead"))))
    (defget ctx ep "tFoot" (this) (when-tag this "table" (wrap ctx (first-child-tag node "tfoot"))))
    (defget ctx ep "tBodies" (this)
      (when-tag this "table" (make-collection ctx (lambda () (child-tags node "tbody")))))
    (defget ctx ep "rows" (this)
      (let ((node (n this)))
        (cond ((tag= node "table") (make-collection ctx (lambda () (table-rows node))))
              ((or (tag= node "thead") (tag= node "tbody") (tag= node "tfoot"))
               (make-collection ctx (lambda () (section-rows node))))
              (t js:*undefined*))))
    (defget ctx ep "cells" (this)
      (let ((node (n this)))
        (if (tag= node "tr") (make-collection ctx (lambda () (row-cells node))) js:*undefined*)))
    (defget ctx ep "rowIndex" (this)
      (let ((node (n this)))
        (if (tag= node "tr")
            (let* ((table (loop for a = (h:dnode-parent node) then (h:dnode-parent a)
                                while a when (tag= a "table") return a)))
              (num (if table (or (position node (table-rows table)) -1) -1)))
            js:*undefined*)))
    (defget ctx ep "sectionRowIndex" (this)
      (let ((node (n this)))
        (if (tag= node "tr")
            (let ((p (h:dnode-parent node)))
              (num (if p (or (position node (section-rows p)) -1) -1)))
            js:*undefined*)))
    ;; create/delete caption/tHead/tFoot
    (flet ((ensure-section (node name at-front)
             (or (first-child-tag node name)
                 (let ((el (h:make-element name)))
                   (setf (gethash el (context-owner-docs ctx)) node)
                   (if at-front (insert-child-at node el 0) (h:dom-append node el))
                   (setf (context-dirty ctx) t) el))))
      (defmethod* ctx ep "createCaption" 0 (this a)
        (when-tag this "table" (wrap ctx (ensure-section node "caption" t))))
      (defmethod* ctx ep "createTHead" 0 (this a)
        (when-tag this "table" (wrap ctx (ensure-section node "thead" t))))
      (defmethod* ctx ep "createTFoot" 0 (this a)
        (when-tag this "table" (wrap ctx (ensure-section node "tfoot" nil)))))
    (flet ((del (node name) (let ((s (first-child-tag node name)))
                              (when s (h:dom-remove s) (setf (context-dirty ctx) t)))))
      (defmethod* ctx ep "deleteCaption" 0 (this a) (when-tag this "table" (del node "caption")) js:*undefined*)
      (defmethod* ctx ep "deleteTHead" 0 (this a) (when-tag this "table" (del node "thead")) js:*undefined*)
      (defmethod* ctx ep "deleteTFoot" 0 (this a) (when-tag this "table" (del node "tfoot")) js:*undefined*))
    ;; insertRow / deleteRow (table + section)
    (defmethod* ctx ep "insertRow" 1 (this a)
      (let* ((node (n this)) (index (if (js:js-undefined-p (arg a 0)) -1 (int-arg a 0))))
        (cond
          ((or (tag= node "thead") (tag= node "tbody") (tag= node "tfoot"))
           (let ((tr (h:make-element "tr")))
             (setf (gethash tr (context-owner-docs ctx)) node)
             (insert-child-at node tr index) (setf (context-dirty ctx) t) (wrap ctx tr)))
          ((tag= node "table")
           (let* ((rows (table-rows node)) (tr (h:make-element "tr")))
             (setf (gethash tr (context-owner-docs ctx)) node)
             (cond
               ((null rows)                          ; empty: make a tbody
                (let ((tb (or (first-child-tag node "tbody")
                              (let ((b (h:make-element "tbody"))) (h:dom-append node b) b))))
                  (h:dom-append tb tr)))
               ((or (< index 0) (>= index (length rows)))  ; append after last row
                (h:dom-append (h:dnode-parent (car (last rows))) tr))
               (t (let ((ref (nth index rows)))            ; before rows[index], same parent
                    (h:dom-insert-before (h:dnode-parent ref) tr ref))))
             (setf (context-dirty ctx) t) (wrap ctx tr)))
          (t js:*undefined*))))
    (defmethod* ctx ep "deleteRow" 1 (this a)
      (let* ((node (n this)) (index (int-arg a 0))
             (rows (cond ((tag= node "table") (table-rows node))
                         ((or (tag= node "thead") (tag= node "tbody") (tag= node "tfoot"))
                          (section-rows node)) (t nil))))
        (when (and rows (< -1 index (length rows)))
          (h:dom-remove (nth index rows)) (setf (context-dirty ctx) t)))
      js:*undefined*)
    ;; insertCell / deleteCell (tr)
    (defmethod* ctx ep "insertCell" 1 (this a)
      (let ((node (n this)))
        (if (tag= node "tr")
            (let ((td (h:make-element "td")) (index (if (js:js-undefined-p (arg a 0)) -1 (int-arg a 0))))
              (setf (gethash td (context-owner-docs ctx)) node)
              (insert-child-at node td index) (setf (context-dirty ctx) t) (wrap ctx td))
            js:*undefined*)))
    (defmethod* ctx ep "deleteCell" 1 (this a)
      (let ((node (n this)))
        (when (tag= node "tr")
          (let ((cells (row-cells node)) (index (int-arg a 0)))
            (when (< -1 index (length cells)) (h:dom-remove (nth index cells)) (setf (context-dirty ctx) t)))))
      js:*undefined*)))
