;;;; src/render/case-map.lisp - Unicode full case mapping supplement for
;;;; CSS text-transform.  GENERATED from UnicodeData.txt + SpecialCasing.txt
;;;; (unconditional entries only).  Only mappings that differ from SBCL's
;;;; bijective CHAR-UPCASE / CHAR-DOWNCASE; callers fall back to those.
(in-package #:weft.render)

(defparameter *full-upcase-map*
  (let ((h (make-hash-table :test 'eql)))
    (setf (gethash #xB5 h) (coerce (list (code-char #x39C)) 'string))
    (setf (gethash #xDF h) (coerce (list (code-char #x53) (code-char #x53)) 'string))
    (setf (gethash #x131 h) (coerce (list (code-char #x49)) 'string))
    (setf (gethash #x149 h) (coerce (list (code-char #x2BC) (code-char #x4E)) 'string))
    (setf (gethash #x17F h) (coerce (list (code-char #x53)) 'string))
    (setf (gethash #x19B h) (coerce (list (code-char #xA7DC)) 'string))
    (setf (gethash #x1F0 h) (coerce (list (code-char #x4A) (code-char #x30C)) 'string))
    (setf (gethash #x264 h) (coerce (list (code-char #xA7CB)) 'string))
    (setf (gethash #x282 h) (coerce (list (code-char #xA7C5)) 'string))
    (setf (gethash #x345 h) (coerce (list (code-char #x399)) 'string))
    (setf (gethash #x390 h) (coerce (list (code-char #x399) (code-char #x308) (code-char #x301)) 'string))
    (setf (gethash #x3B0 h) (coerce (list (code-char #x3A5) (code-char #x308) (code-char #x301)) 'string))
    (setf (gethash #x3C2 h) (coerce (list (code-char #x3A3)) 'string))
    (setf (gethash #x3D0 h) (coerce (list (code-char #x392)) 'string))
    (setf (gethash #x3D1 h) (coerce (list (code-char #x398)) 'string))
    (setf (gethash #x3D5 h) (coerce (list (code-char #x3A6)) 'string))
    (setf (gethash #x3D6 h) (coerce (list (code-char #x3A0)) 'string))
    (setf (gethash #x3F0 h) (coerce (list (code-char #x39A)) 'string))
    (setf (gethash #x3F1 h) (coerce (list (code-char #x3A1)) 'string))
    (setf (gethash #x3F5 h) (coerce (list (code-char #x395)) 'string))
    (setf (gethash #x587 h) (coerce (list (code-char #x535) (code-char #x552)) 'string))
    (setf (gethash #x10D0 h) (coerce (list (code-char #x1C90)) 'string))
    (setf (gethash #x10D1 h) (coerce (list (code-char #x1C91)) 'string))
    (setf (gethash #x10D2 h) (coerce (list (code-char #x1C92)) 'string))
    (setf (gethash #x10D3 h) (coerce (list (code-char #x1C93)) 'string))
    (setf (gethash #x10D4 h) (coerce (list (code-char #x1C94)) 'string))
    (setf (gethash #x10D5 h) (coerce (list (code-char #x1C95)) 'string))
    (setf (gethash #x10D6 h) (coerce (list (code-char #x1C96)) 'string))
    (setf (gethash #x10D7 h) (coerce (list (code-char #x1C97)) 'string))
    (setf (gethash #x10D8 h) (coerce (list (code-char #x1C98)) 'string))
    (setf (gethash #x10D9 h) (coerce (list (code-char #x1C99)) 'string))
    (setf (gethash #x10DA h) (coerce (list (code-char #x1C9A)) 'string))
    (setf (gethash #x10DB h) (coerce (list (code-char #x1C9B)) 'string))
    (setf (gethash #x10DC h) (coerce (list (code-char #x1C9C)) 'string))
    (setf (gethash #x10DD h) (coerce (list (code-char #x1C9D)) 'string))
    (setf (gethash #x10DE h) (coerce (list (code-char #x1C9E)) 'string))
    (setf (gethash #x10DF h) (coerce (list (code-char #x1C9F)) 'string))
    (setf (gethash #x10E0 h) (coerce (list (code-char #x1CA0)) 'string))
    (setf (gethash #x10E1 h) (coerce (list (code-char #x1CA1)) 'string))
    (setf (gethash #x10E2 h) (coerce (list (code-char #x1CA2)) 'string))
    (setf (gethash #x10E3 h) (coerce (list (code-char #x1CA3)) 'string))
    (setf (gethash #x10E4 h) (coerce (list (code-char #x1CA4)) 'string))
    (setf (gethash #x10E5 h) (coerce (list (code-char #x1CA5)) 'string))
    (setf (gethash #x10E6 h) (coerce (list (code-char #x1CA6)) 'string))
    (setf (gethash #x10E7 h) (coerce (list (code-char #x1CA7)) 'string))
    (setf (gethash #x10E8 h) (coerce (list (code-char #x1CA8)) 'string))
    (setf (gethash #x10E9 h) (coerce (list (code-char #x1CA9)) 'string))
    (setf (gethash #x10EA h) (coerce (list (code-char #x1CAA)) 'string))
    (setf (gethash #x10EB h) (coerce (list (code-char #x1CAB)) 'string))
    (setf (gethash #x10EC h) (coerce (list (code-char #x1CAC)) 'string))
    (setf (gethash #x10ED h) (coerce (list (code-char #x1CAD)) 'string))
    (setf (gethash #x10EE h) (coerce (list (code-char #x1CAE)) 'string))
    (setf (gethash #x10EF h) (coerce (list (code-char #x1CAF)) 'string))
    (setf (gethash #x10F0 h) (coerce (list (code-char #x1CB0)) 'string))
    (setf (gethash #x10F1 h) (coerce (list (code-char #x1CB1)) 'string))
    (setf (gethash #x10F2 h) (coerce (list (code-char #x1CB2)) 'string))
    (setf (gethash #x10F3 h) (coerce (list (code-char #x1CB3)) 'string))
    (setf (gethash #x10F4 h) (coerce (list (code-char #x1CB4)) 'string))
    (setf (gethash #x10F5 h) (coerce (list (code-char #x1CB5)) 'string))
    (setf (gethash #x10F6 h) (coerce (list (code-char #x1CB6)) 'string))
    (setf (gethash #x10F7 h) (coerce (list (code-char #x1CB7)) 'string))
    (setf (gethash #x10F8 h) (coerce (list (code-char #x1CB8)) 'string))
    (setf (gethash #x10F9 h) (coerce (list (code-char #x1CB9)) 'string))
    (setf (gethash #x10FA h) (coerce (list (code-char #x1CBA)) 'string))
    (setf (gethash #x10FD h) (coerce (list (code-char #x1CBD)) 'string))
    (setf (gethash #x10FE h) (coerce (list (code-char #x1CBE)) 'string))
    (setf (gethash #x10FF h) (coerce (list (code-char #x1CBF)) 'string))
    (setf (gethash #x1C80 h) (coerce (list (code-char #x412)) 'string))
    (setf (gethash #x1C81 h) (coerce (list (code-char #x414)) 'string))
    (setf (gethash #x1C82 h) (coerce (list (code-char #x41E)) 'string))
    (setf (gethash #x1C83 h) (coerce (list (code-char #x421)) 'string))
    (setf (gethash #x1C84 h) (coerce (list (code-char #x422)) 'string))
    (setf (gethash #x1C85 h) (coerce (list (code-char #x422)) 'string))
    (setf (gethash #x1C86 h) (coerce (list (code-char #x42A)) 'string))
    (setf (gethash #x1C87 h) (coerce (list (code-char #x462)) 'string))
    (setf (gethash #x1C88 h) (coerce (list (code-char #xA64A)) 'string))
    (setf (gethash #x1C8A h) (coerce (list (code-char #x1C89)) 'string))
    (setf (gethash #x1D8E h) (coerce (list (code-char #xA7C6)) 'string))
    (setf (gethash #x1E96 h) (coerce (list (code-char #x48) (code-char #x331)) 'string))
    (setf (gethash #x1E97 h) (coerce (list (code-char #x54) (code-char #x308)) 'string))
    (setf (gethash #x1E98 h) (coerce (list (code-char #x57) (code-char #x30A)) 'string))
    (setf (gethash #x1E99 h) (coerce (list (code-char #x59) (code-char #x30A)) 'string))
    (setf (gethash #x1E9A h) (coerce (list (code-char #x41) (code-char #x2BE)) 'string))
    (setf (gethash #x1E9B h) (coerce (list (code-char #x1E60)) 'string))
    (setf (gethash #x1F50 h) (coerce (list (code-char #x3A5) (code-char #x313)) 'string))
    (setf (gethash #x1F52 h) (coerce (list (code-char #x3A5) (code-char #x313) (code-char #x300)) 'string))
    (setf (gethash #x1F54 h) (coerce (list (code-char #x3A5) (code-char #x313) (code-char #x301)) 'string))
    (setf (gethash #x1F56 h) (coerce (list (code-char #x3A5) (code-char #x313) (code-char #x342)) 'string))
    (setf (gethash #x1F80 h) (coerce (list (code-char #x1F08) (code-char #x399)) 'string))
    (setf (gethash #x1F81 h) (coerce (list (code-char #x1F09) (code-char #x399)) 'string))
    (setf (gethash #x1F82 h) (coerce (list (code-char #x1F0A) (code-char #x399)) 'string))
    (setf (gethash #x1F83 h) (coerce (list (code-char #x1F0B) (code-char #x399)) 'string))
    (setf (gethash #x1F84 h) (coerce (list (code-char #x1F0C) (code-char #x399)) 'string))
    (setf (gethash #x1F85 h) (coerce (list (code-char #x1F0D) (code-char #x399)) 'string))
    (setf (gethash #x1F86 h) (coerce (list (code-char #x1F0E) (code-char #x399)) 'string))
    (setf (gethash #x1F87 h) (coerce (list (code-char #x1F0F) (code-char #x399)) 'string))
    (setf (gethash #x1F88 h) (coerce (list (code-char #x1F08) (code-char #x399)) 'string))
    (setf (gethash #x1F89 h) (coerce (list (code-char #x1F09) (code-char #x399)) 'string))
    (setf (gethash #x1F8A h) (coerce (list (code-char #x1F0A) (code-char #x399)) 'string))
    (setf (gethash #x1F8B h) (coerce (list (code-char #x1F0B) (code-char #x399)) 'string))
    (setf (gethash #x1F8C h) (coerce (list (code-char #x1F0C) (code-char #x399)) 'string))
    (setf (gethash #x1F8D h) (coerce (list (code-char #x1F0D) (code-char #x399)) 'string))
    (setf (gethash #x1F8E h) (coerce (list (code-char #x1F0E) (code-char #x399)) 'string))
    (setf (gethash #x1F8F h) (coerce (list (code-char #x1F0F) (code-char #x399)) 'string))
    (setf (gethash #x1F90 h) (coerce (list (code-char #x1F28) (code-char #x399)) 'string))
    (setf (gethash #x1F91 h) (coerce (list (code-char #x1F29) (code-char #x399)) 'string))
    (setf (gethash #x1F92 h) (coerce (list (code-char #x1F2A) (code-char #x399)) 'string))
    (setf (gethash #x1F93 h) (coerce (list (code-char #x1F2B) (code-char #x399)) 'string))
    (setf (gethash #x1F94 h) (coerce (list (code-char #x1F2C) (code-char #x399)) 'string))
    (setf (gethash #x1F95 h) (coerce (list (code-char #x1F2D) (code-char #x399)) 'string))
    (setf (gethash #x1F96 h) (coerce (list (code-char #x1F2E) (code-char #x399)) 'string))
    (setf (gethash #x1F97 h) (coerce (list (code-char #x1F2F) (code-char #x399)) 'string))
    (setf (gethash #x1F98 h) (coerce (list (code-char #x1F28) (code-char #x399)) 'string))
    (setf (gethash #x1F99 h) (coerce (list (code-char #x1F29) (code-char #x399)) 'string))
    (setf (gethash #x1F9A h) (coerce (list (code-char #x1F2A) (code-char #x399)) 'string))
    (setf (gethash #x1F9B h) (coerce (list (code-char #x1F2B) (code-char #x399)) 'string))
    (setf (gethash #x1F9C h) (coerce (list (code-char #x1F2C) (code-char #x399)) 'string))
    (setf (gethash #x1F9D h) (coerce (list (code-char #x1F2D) (code-char #x399)) 'string))
    (setf (gethash #x1F9E h) (coerce (list (code-char #x1F2E) (code-char #x399)) 'string))
    (setf (gethash #x1F9F h) (coerce (list (code-char #x1F2F) (code-char #x399)) 'string))
    (setf (gethash #x1FA0 h) (coerce (list (code-char #x1F68) (code-char #x399)) 'string))
    (setf (gethash #x1FA1 h) (coerce (list (code-char #x1F69) (code-char #x399)) 'string))
    (setf (gethash #x1FA2 h) (coerce (list (code-char #x1F6A) (code-char #x399)) 'string))
    (setf (gethash #x1FA3 h) (coerce (list (code-char #x1F6B) (code-char #x399)) 'string))
    (setf (gethash #x1FA4 h) (coerce (list (code-char #x1F6C) (code-char #x399)) 'string))
    (setf (gethash #x1FA5 h) (coerce (list (code-char #x1F6D) (code-char #x399)) 'string))
    (setf (gethash #x1FA6 h) (coerce (list (code-char #x1F6E) (code-char #x399)) 'string))
    (setf (gethash #x1FA7 h) (coerce (list (code-char #x1F6F) (code-char #x399)) 'string))
    (setf (gethash #x1FA8 h) (coerce (list (code-char #x1F68) (code-char #x399)) 'string))
    (setf (gethash #x1FA9 h) (coerce (list (code-char #x1F69) (code-char #x399)) 'string))
    (setf (gethash #x1FAA h) (coerce (list (code-char #x1F6A) (code-char #x399)) 'string))
    (setf (gethash #x1FAB h) (coerce (list (code-char #x1F6B) (code-char #x399)) 'string))
    (setf (gethash #x1FAC h) (coerce (list (code-char #x1F6C) (code-char #x399)) 'string))
    (setf (gethash #x1FAD h) (coerce (list (code-char #x1F6D) (code-char #x399)) 'string))
    (setf (gethash #x1FAE h) (coerce (list (code-char #x1F6E) (code-char #x399)) 'string))
    (setf (gethash #x1FAF h) (coerce (list (code-char #x1F6F) (code-char #x399)) 'string))
    (setf (gethash #x1FB2 h) (coerce (list (code-char #x1FBA) (code-char #x399)) 'string))
    (setf (gethash #x1FB3 h) (coerce (list (code-char #x391) (code-char #x399)) 'string))
    (setf (gethash #x1FB4 h) (coerce (list (code-char #x386) (code-char #x399)) 'string))
    (setf (gethash #x1FB6 h) (coerce (list (code-char #x391) (code-char #x342)) 'string))
    (setf (gethash #x1FB7 h) (coerce (list (code-char #x391) (code-char #x342) (code-char #x399)) 'string))
    (setf (gethash #x1FBC h) (coerce (list (code-char #x391) (code-char #x399)) 'string))
    (setf (gethash #x1FBE h) (coerce (list (code-char #x399)) 'string))
    (setf (gethash #x1FC2 h) (coerce (list (code-char #x1FCA) (code-char #x399)) 'string))
    (setf (gethash #x1FC3 h) (coerce (list (code-char #x397) (code-char #x399)) 'string))
    (setf (gethash #x1FC4 h) (coerce (list (code-char #x389) (code-char #x399)) 'string))
    (setf (gethash #x1FC6 h) (coerce (list (code-char #x397) (code-char #x342)) 'string))
    (setf (gethash #x1FC7 h) (coerce (list (code-char #x397) (code-char #x342) (code-char #x399)) 'string))
    (setf (gethash #x1FCC h) (coerce (list (code-char #x397) (code-char #x399)) 'string))
    (setf (gethash #x1FD2 h) (coerce (list (code-char #x399) (code-char #x308) (code-char #x300)) 'string))
    (setf (gethash #x1FD3 h) (coerce (list (code-char #x399) (code-char #x308) (code-char #x301)) 'string))
    (setf (gethash #x1FD6 h) (coerce (list (code-char #x399) (code-char #x342)) 'string))
    (setf (gethash #x1FD7 h) (coerce (list (code-char #x399) (code-char #x308) (code-char #x342)) 'string))
    (setf (gethash #x1FE2 h) (coerce (list (code-char #x3A5) (code-char #x308) (code-char #x300)) 'string))
    (setf (gethash #x1FE3 h) (coerce (list (code-char #x3A5) (code-char #x308) (code-char #x301)) 'string))
    (setf (gethash #x1FE4 h) (coerce (list (code-char #x3A1) (code-char #x313)) 'string))
    (setf (gethash #x1FE6 h) (coerce (list (code-char #x3A5) (code-char #x342)) 'string))
    (setf (gethash #x1FE7 h) (coerce (list (code-char #x3A5) (code-char #x308) (code-char #x342)) 'string))
    (setf (gethash #x1FF2 h) (coerce (list (code-char #x1FFA) (code-char #x399)) 'string))
    (setf (gethash #x1FF3 h) (coerce (list (code-char #x3A9) (code-char #x399)) 'string))
    (setf (gethash #x1FF4 h) (coerce (list (code-char #x38F) (code-char #x399)) 'string))
    (setf (gethash #x1FF6 h) (coerce (list (code-char #x3A9) (code-char #x342)) 'string))
    (setf (gethash #x1FF7 h) (coerce (list (code-char #x3A9) (code-char #x342) (code-char #x399)) 'string))
    (setf (gethash #x1FFC h) (coerce (list (code-char #x3A9) (code-char #x399)) 'string))
    (setf (gethash #x2170 h) (coerce (list (code-char #x2160)) 'string))
    (setf (gethash #x2171 h) (coerce (list (code-char #x2161)) 'string))
    (setf (gethash #x2172 h) (coerce (list (code-char #x2162)) 'string))
    (setf (gethash #x2173 h) (coerce (list (code-char #x2163)) 'string))
    (setf (gethash #x2174 h) (coerce (list (code-char #x2164)) 'string))
    (setf (gethash #x2175 h) (coerce (list (code-char #x2165)) 'string))
    (setf (gethash #x2176 h) (coerce (list (code-char #x2166)) 'string))
    (setf (gethash #x2177 h) (coerce (list (code-char #x2167)) 'string))
    (setf (gethash #x2178 h) (coerce (list (code-char #x2168)) 'string))
    (setf (gethash #x2179 h) (coerce (list (code-char #x2169)) 'string))
    (setf (gethash #x217A h) (coerce (list (code-char #x216A)) 'string))
    (setf (gethash #x217B h) (coerce (list (code-char #x216B)) 'string))
    (setf (gethash #x217C h) (coerce (list (code-char #x216C)) 'string))
    (setf (gethash #x217D h) (coerce (list (code-char #x216D)) 'string))
    (setf (gethash #x217E h) (coerce (list (code-char #x216E)) 'string))
    (setf (gethash #x217F h) (coerce (list (code-char #x216F)) 'string))
    (setf (gethash #x24D0 h) (coerce (list (code-char #x24B6)) 'string))
    (setf (gethash #x24D1 h) (coerce (list (code-char #x24B7)) 'string))
    (setf (gethash #x24D2 h) (coerce (list (code-char #x24B8)) 'string))
    (setf (gethash #x24D3 h) (coerce (list (code-char #x24B9)) 'string))
    (setf (gethash #x24D4 h) (coerce (list (code-char #x24BA)) 'string))
    (setf (gethash #x24D5 h) (coerce (list (code-char #x24BB)) 'string))
    (setf (gethash #x24D6 h) (coerce (list (code-char #x24BC)) 'string))
    (setf (gethash #x24D7 h) (coerce (list (code-char #x24BD)) 'string))
    (setf (gethash #x24D8 h) (coerce (list (code-char #x24BE)) 'string))
    (setf (gethash #x24D9 h) (coerce (list (code-char #x24BF)) 'string))
    (setf (gethash #x24DA h) (coerce (list (code-char #x24C0)) 'string))
    (setf (gethash #x24DB h) (coerce (list (code-char #x24C1)) 'string))
    (setf (gethash #x24DC h) (coerce (list (code-char #x24C2)) 'string))
    (setf (gethash #x24DD h) (coerce (list (code-char #x24C3)) 'string))
    (setf (gethash #x24DE h) (coerce (list (code-char #x24C4)) 'string))
    (setf (gethash #x24DF h) (coerce (list (code-char #x24C5)) 'string))
    (setf (gethash #x24E0 h) (coerce (list (code-char #x24C6)) 'string))
    (setf (gethash #x24E1 h) (coerce (list (code-char #x24C7)) 'string))
    (setf (gethash #x24E2 h) (coerce (list (code-char #x24C8)) 'string))
    (setf (gethash #x24E3 h) (coerce (list (code-char #x24C9)) 'string))
    (setf (gethash #x24E4 h) (coerce (list (code-char #x24CA)) 'string))
    (setf (gethash #x24E5 h) (coerce (list (code-char #x24CB)) 'string))
    (setf (gethash #x24E6 h) (coerce (list (code-char #x24CC)) 'string))
    (setf (gethash #x24E7 h) (coerce (list (code-char #x24CD)) 'string))
    (setf (gethash #x24E8 h) (coerce (list (code-char #x24CE)) 'string))
    (setf (gethash #x24E9 h) (coerce (list (code-char #x24CF)) 'string))
    (setf (gethash #x2C5F h) (coerce (list (code-char #x2C2F)) 'string))
    (setf (gethash #xA794 h) (coerce (list (code-char #xA7C4)) 'string))
    (setf (gethash #xA7B9 h) (coerce (list (code-char #xA7B8)) 'string))
    (setf (gethash #xA7BB h) (coerce (list (code-char #xA7BA)) 'string))
    (setf (gethash #xA7BD h) (coerce (list (code-char #xA7BC)) 'string))
    (setf (gethash #xA7BF h) (coerce (list (code-char #xA7BE)) 'string))
    (setf (gethash #xA7C1 h) (coerce (list (code-char #xA7C0)) 'string))
    (setf (gethash #xA7C3 h) (coerce (list (code-char #xA7C2)) 'string))
    (setf (gethash #xA7C8 h) (coerce (list (code-char #xA7C7)) 'string))
    (setf (gethash #xA7CA h) (coerce (list (code-char #xA7C9)) 'string))
    (setf (gethash #xA7CD h) (coerce (list (code-char #xA7CC)) 'string))
    (setf (gethash #xA7CF h) (coerce (list (code-char #xA7CE)) 'string))
    (setf (gethash #xA7D1 h) (coerce (list (code-char #xA7D0)) 'string))
    (setf (gethash #xA7D3 h) (coerce (list (code-char #xA7D2)) 'string))
    (setf (gethash #xA7D5 h) (coerce (list (code-char #xA7D4)) 'string))
    (setf (gethash #xA7D7 h) (coerce (list (code-char #xA7D6)) 'string))
    (setf (gethash #xA7D9 h) (coerce (list (code-char #xA7D8)) 'string))
    (setf (gethash #xA7DB h) (coerce (list (code-char #xA7DA)) 'string))
    (setf (gethash #xA7F6 h) (coerce (list (code-char #xA7F5)) 'string))
    (setf (gethash #xFB00 h) (coerce (list (code-char #x46) (code-char #x46)) 'string))
    (setf (gethash #xFB01 h) (coerce (list (code-char #x46) (code-char #x49)) 'string))
    (setf (gethash #xFB02 h) (coerce (list (code-char #x46) (code-char #x4C)) 'string))
    (setf (gethash #xFB03 h) (coerce (list (code-char #x46) (code-char #x46) (code-char #x49)) 'string))
    (setf (gethash #xFB04 h) (coerce (list (code-char #x46) (code-char #x46) (code-char #x4C)) 'string))
    (setf (gethash #xFB05 h) (coerce (list (code-char #x53) (code-char #x54)) 'string))
    (setf (gethash #xFB06 h) (coerce (list (code-char #x53) (code-char #x54)) 'string))
    (setf (gethash #xFB13 h) (coerce (list (code-char #x544) (code-char #x546)) 'string))
    (setf (gethash #xFB14 h) (coerce (list (code-char #x544) (code-char #x535)) 'string))
    (setf (gethash #xFB15 h) (coerce (list (code-char #x544) (code-char #x53B)) 'string))
    (setf (gethash #xFB16 h) (coerce (list (code-char #x54E) (code-char #x546)) 'string))
    (setf (gethash #xFB17 h) (coerce (list (code-char #x544) (code-char #x53D)) 'string))
    (setf (gethash #x10597 h) (coerce (list (code-char #x10570)) 'string))
    (setf (gethash #x10598 h) (coerce (list (code-char #x10571)) 'string))
    (setf (gethash #x10599 h) (coerce (list (code-char #x10572)) 'string))
    (setf (gethash #x1059A h) (coerce (list (code-char #x10573)) 'string))
    (setf (gethash #x1059B h) (coerce (list (code-char #x10574)) 'string))
    (setf (gethash #x1059C h) (coerce (list (code-char #x10575)) 'string))
    (setf (gethash #x1059D h) (coerce (list (code-char #x10576)) 'string))
    (setf (gethash #x1059E h) (coerce (list (code-char #x10577)) 'string))
    (setf (gethash #x1059F h) (coerce (list (code-char #x10578)) 'string))
    (setf (gethash #x105A0 h) (coerce (list (code-char #x10579)) 'string))
    (setf (gethash #x105A1 h) (coerce (list (code-char #x1057A)) 'string))
    (setf (gethash #x105A3 h) (coerce (list (code-char #x1057C)) 'string))
    (setf (gethash #x105A4 h) (coerce (list (code-char #x1057D)) 'string))
    (setf (gethash #x105A5 h) (coerce (list (code-char #x1057E)) 'string))
    (setf (gethash #x105A6 h) (coerce (list (code-char #x1057F)) 'string))
    (setf (gethash #x105A7 h) (coerce (list (code-char #x10580)) 'string))
    (setf (gethash #x105A8 h) (coerce (list (code-char #x10581)) 'string))
    (setf (gethash #x105A9 h) (coerce (list (code-char #x10582)) 'string))
    (setf (gethash #x105AA h) (coerce (list (code-char #x10583)) 'string))
    (setf (gethash #x105AB h) (coerce (list (code-char #x10584)) 'string))
    (setf (gethash #x105AC h) (coerce (list (code-char #x10585)) 'string))
    (setf (gethash #x105AD h) (coerce (list (code-char #x10586)) 'string))
    (setf (gethash #x105AE h) (coerce (list (code-char #x10587)) 'string))
    (setf (gethash #x105AF h) (coerce (list (code-char #x10588)) 'string))
    (setf (gethash #x105B0 h) (coerce (list (code-char #x10589)) 'string))
    (setf (gethash #x105B1 h) (coerce (list (code-char #x1058A)) 'string))
    (setf (gethash #x105B3 h) (coerce (list (code-char #x1058C)) 'string))
    (setf (gethash #x105B4 h) (coerce (list (code-char #x1058D)) 'string))
    (setf (gethash #x105B5 h) (coerce (list (code-char #x1058E)) 'string))
    (setf (gethash #x105B6 h) (coerce (list (code-char #x1058F)) 'string))
    (setf (gethash #x105B7 h) (coerce (list (code-char #x10590)) 'string))
    (setf (gethash #x105B8 h) (coerce (list (code-char #x10591)) 'string))
    (setf (gethash #x105B9 h) (coerce (list (code-char #x10592)) 'string))
    (setf (gethash #x105BB h) (coerce (list (code-char #x10594)) 'string))
    (setf (gethash #x105BC h) (coerce (list (code-char #x10595)) 'string))
    (setf (gethash #x10D70 h) (coerce (list (code-char #x10D50)) 'string))
    (setf (gethash #x10D71 h) (coerce (list (code-char #x10D51)) 'string))
    (setf (gethash #x10D72 h) (coerce (list (code-char #x10D52)) 'string))
    (setf (gethash #x10D73 h) (coerce (list (code-char #x10D53)) 'string))
    (setf (gethash #x10D74 h) (coerce (list (code-char #x10D54)) 'string))
    (setf (gethash #x10D75 h) (coerce (list (code-char #x10D55)) 'string))
    (setf (gethash #x10D76 h) (coerce (list (code-char #x10D56)) 'string))
    (setf (gethash #x10D77 h) (coerce (list (code-char #x10D57)) 'string))
    (setf (gethash #x10D78 h) (coerce (list (code-char #x10D58)) 'string))
    (setf (gethash #x10D79 h) (coerce (list (code-char #x10D59)) 'string))
    (setf (gethash #x10D7A h) (coerce (list (code-char #x10D5A)) 'string))
    (setf (gethash #x10D7B h) (coerce (list (code-char #x10D5B)) 'string))
    (setf (gethash #x10D7C h) (coerce (list (code-char #x10D5C)) 'string))
    (setf (gethash #x10D7D h) (coerce (list (code-char #x10D5D)) 'string))
    (setf (gethash #x10D7E h) (coerce (list (code-char #x10D5E)) 'string))
    (setf (gethash #x10D7F h) (coerce (list (code-char #x10D5F)) 'string))
    (setf (gethash #x10D80 h) (coerce (list (code-char #x10D60)) 'string))
    (setf (gethash #x10D81 h) (coerce (list (code-char #x10D61)) 'string))
    (setf (gethash #x10D82 h) (coerce (list (code-char #x10D62)) 'string))
    (setf (gethash #x10D83 h) (coerce (list (code-char #x10D63)) 'string))
    (setf (gethash #x10D84 h) (coerce (list (code-char #x10D64)) 'string))
    (setf (gethash #x10D85 h) (coerce (list (code-char #x10D65)) 'string))
    (setf (gethash #x16E60 h) (coerce (list (code-char #x16E40)) 'string))
    (setf (gethash #x16E61 h) (coerce (list (code-char #x16E41)) 'string))
    (setf (gethash #x16E62 h) (coerce (list (code-char #x16E42)) 'string))
    (setf (gethash #x16E63 h) (coerce (list (code-char #x16E43)) 'string))
    (setf (gethash #x16E64 h) (coerce (list (code-char #x16E44)) 'string))
    (setf (gethash #x16E65 h) (coerce (list (code-char #x16E45)) 'string))
    (setf (gethash #x16E66 h) (coerce (list (code-char #x16E46)) 'string))
    (setf (gethash #x16E67 h) (coerce (list (code-char #x16E47)) 'string))
    (setf (gethash #x16E68 h) (coerce (list (code-char #x16E48)) 'string))
    (setf (gethash #x16E69 h) (coerce (list (code-char #x16E49)) 'string))
    (setf (gethash #x16E6A h) (coerce (list (code-char #x16E4A)) 'string))
    (setf (gethash #x16E6B h) (coerce (list (code-char #x16E4B)) 'string))
    (setf (gethash #x16E6C h) (coerce (list (code-char #x16E4C)) 'string))
    (setf (gethash #x16E6D h) (coerce (list (code-char #x16E4D)) 'string))
    (setf (gethash #x16E6E h) (coerce (list (code-char #x16E4E)) 'string))
    (setf (gethash #x16E6F h) (coerce (list (code-char #x16E4F)) 'string))
    (setf (gethash #x16E70 h) (coerce (list (code-char #x16E50)) 'string))
    (setf (gethash #x16E71 h) (coerce (list (code-char #x16E51)) 'string))
    (setf (gethash #x16E72 h) (coerce (list (code-char #x16E52)) 'string))
    (setf (gethash #x16E73 h) (coerce (list (code-char #x16E53)) 'string))
    (setf (gethash #x16E74 h) (coerce (list (code-char #x16E54)) 'string))
    (setf (gethash #x16E75 h) (coerce (list (code-char #x16E55)) 'string))
    (setf (gethash #x16E76 h) (coerce (list (code-char #x16E56)) 'string))
    (setf (gethash #x16E77 h) (coerce (list (code-char #x16E57)) 'string))
    (setf (gethash #x16E78 h) (coerce (list (code-char #x16E58)) 'string))
    (setf (gethash #x16E79 h) (coerce (list (code-char #x16E59)) 'string))
    (setf (gethash #x16E7A h) (coerce (list (code-char #x16E5A)) 'string))
    (setf (gethash #x16E7B h) (coerce (list (code-char #x16E5B)) 'string))
    (setf (gethash #x16E7C h) (coerce (list (code-char #x16E5C)) 'string))
    (setf (gethash #x16E7D h) (coerce (list (code-char #x16E5D)) 'string))
    (setf (gethash #x16E7E h) (coerce (list (code-char #x16E5E)) 'string))
    (setf (gethash #x16E7F h) (coerce (list (code-char #x16E5F)) 'string))
    (setf (gethash #x16EBB h) (coerce (list (code-char #x16EA0)) 'string))
    (setf (gethash #x16EBC h) (coerce (list (code-char #x16EA1)) 'string))
    (setf (gethash #x16EBD h) (coerce (list (code-char #x16EA2)) 'string))
    (setf (gethash #x16EBE h) (coerce (list (code-char #x16EA3)) 'string))
    (setf (gethash #x16EBF h) (coerce (list (code-char #x16EA4)) 'string))
    (setf (gethash #x16EC0 h) (coerce (list (code-char #x16EA5)) 'string))
    (setf (gethash #x16EC1 h) (coerce (list (code-char #x16EA6)) 'string))
    (setf (gethash #x16EC2 h) (coerce (list (code-char #x16EA7)) 'string))
    (setf (gethash #x16EC3 h) (coerce (list (code-char #x16EA8)) 'string))
    (setf (gethash #x16EC4 h) (coerce (list (code-char #x16EA9)) 'string))
    (setf (gethash #x16EC5 h) (coerce (list (code-char #x16EAA)) 'string))
    (setf (gethash #x16EC6 h) (coerce (list (code-char #x16EAB)) 'string))
    (setf (gethash #x16EC7 h) (coerce (list (code-char #x16EAC)) 'string))
    (setf (gethash #x16EC8 h) (coerce (list (code-char #x16EAD)) 'string))
    (setf (gethash #x16EC9 h) (coerce (list (code-char #x16EAE)) 'string))
    (setf (gethash #x16ECA h) (coerce (list (code-char #x16EAF)) 'string))
    (setf (gethash #x16ECB h) (coerce (list (code-char #x16EB0)) 'string))
    (setf (gethash #x16ECC h) (coerce (list (code-char #x16EB1)) 'string))
    (setf (gethash #x16ECD h) (coerce (list (code-char #x16EB2)) 'string))
    (setf (gethash #x16ECE h) (coerce (list (code-char #x16EB3)) 'string))
    (setf (gethash #x16ECF h) (coerce (list (code-char #x16EB4)) 'string))
    (setf (gethash #x16ED0 h) (coerce (list (code-char #x16EB5)) 'string))
    (setf (gethash #x16ED1 h) (coerce (list (code-char #x16EB6)) 'string))
    (setf (gethash #x16ED2 h) (coerce (list (code-char #x16EB7)) 'string))
    (setf (gethash #x16ED3 h) (coerce (list (code-char #x16EB8)) 'string))
    h))

(defparameter *full-downcase-map*
  (let ((h (make-hash-table :test 'eql)))
    (setf (gethash #x130 h) (coerce (list (code-char #x69) (code-char #x307)) 'string))
    (setf (gethash #x3F4 h) (coerce (list (code-char #x3B8)) 'string))
    (setf (gethash #x1C89 h) (coerce (list (code-char #x1C8A)) 'string))
    (setf (gethash #x1C90 h) (coerce (list (code-char #x10D0)) 'string))
    (setf (gethash #x1C91 h) (coerce (list (code-char #x10D1)) 'string))
    (setf (gethash #x1C92 h) (coerce (list (code-char #x10D2)) 'string))
    (setf (gethash #x1C93 h) (coerce (list (code-char #x10D3)) 'string))
    (setf (gethash #x1C94 h) (coerce (list (code-char #x10D4)) 'string))
    (setf (gethash #x1C95 h) (coerce (list (code-char #x10D5)) 'string))
    (setf (gethash #x1C96 h) (coerce (list (code-char #x10D6)) 'string))
    (setf (gethash #x1C97 h) (coerce (list (code-char #x10D7)) 'string))
    (setf (gethash #x1C98 h) (coerce (list (code-char #x10D8)) 'string))
    (setf (gethash #x1C99 h) (coerce (list (code-char #x10D9)) 'string))
    (setf (gethash #x1C9A h) (coerce (list (code-char #x10DA)) 'string))
    (setf (gethash #x1C9B h) (coerce (list (code-char #x10DB)) 'string))
    (setf (gethash #x1C9C h) (coerce (list (code-char #x10DC)) 'string))
    (setf (gethash #x1C9D h) (coerce (list (code-char #x10DD)) 'string))
    (setf (gethash #x1C9E h) (coerce (list (code-char #x10DE)) 'string))
    (setf (gethash #x1C9F h) (coerce (list (code-char #x10DF)) 'string))
    (setf (gethash #x1CA0 h) (coerce (list (code-char #x10E0)) 'string))
    (setf (gethash #x1CA1 h) (coerce (list (code-char #x10E1)) 'string))
    (setf (gethash #x1CA2 h) (coerce (list (code-char #x10E2)) 'string))
    (setf (gethash #x1CA3 h) (coerce (list (code-char #x10E3)) 'string))
    (setf (gethash #x1CA4 h) (coerce (list (code-char #x10E4)) 'string))
    (setf (gethash #x1CA5 h) (coerce (list (code-char #x10E5)) 'string))
    (setf (gethash #x1CA6 h) (coerce (list (code-char #x10E6)) 'string))
    (setf (gethash #x1CA7 h) (coerce (list (code-char #x10E7)) 'string))
    (setf (gethash #x1CA8 h) (coerce (list (code-char #x10E8)) 'string))
    (setf (gethash #x1CA9 h) (coerce (list (code-char #x10E9)) 'string))
    (setf (gethash #x1CAA h) (coerce (list (code-char #x10EA)) 'string))
    (setf (gethash #x1CAB h) (coerce (list (code-char #x10EB)) 'string))
    (setf (gethash #x1CAC h) (coerce (list (code-char #x10EC)) 'string))
    (setf (gethash #x1CAD h) (coerce (list (code-char #x10ED)) 'string))
    (setf (gethash #x1CAE h) (coerce (list (code-char #x10EE)) 'string))
    (setf (gethash #x1CAF h) (coerce (list (code-char #x10EF)) 'string))
    (setf (gethash #x1CB0 h) (coerce (list (code-char #x10F0)) 'string))
    (setf (gethash #x1CB1 h) (coerce (list (code-char #x10F1)) 'string))
    (setf (gethash #x1CB2 h) (coerce (list (code-char #x10F2)) 'string))
    (setf (gethash #x1CB3 h) (coerce (list (code-char #x10F3)) 'string))
    (setf (gethash #x1CB4 h) (coerce (list (code-char #x10F4)) 'string))
    (setf (gethash #x1CB5 h) (coerce (list (code-char #x10F5)) 'string))
    (setf (gethash #x1CB6 h) (coerce (list (code-char #x10F6)) 'string))
    (setf (gethash #x1CB7 h) (coerce (list (code-char #x10F7)) 'string))
    (setf (gethash #x1CB8 h) (coerce (list (code-char #x10F8)) 'string))
    (setf (gethash #x1CB9 h) (coerce (list (code-char #x10F9)) 'string))
    (setf (gethash #x1CBA h) (coerce (list (code-char #x10FA)) 'string))
    (setf (gethash #x1CBD h) (coerce (list (code-char #x10FD)) 'string))
    (setf (gethash #x1CBE h) (coerce (list (code-char #x10FE)) 'string))
    (setf (gethash #x1CBF h) (coerce (list (code-char #x10FF)) 'string))
    (setf (gethash #x1E9E h) (coerce (list (code-char #xDF)) 'string))
    (setf (gethash #x1F88 h) (coerce (list (code-char #x1F80)) 'string))
    (setf (gethash #x1F89 h) (coerce (list (code-char #x1F81)) 'string))
    (setf (gethash #x1F8A h) (coerce (list (code-char #x1F82)) 'string))
    (setf (gethash #x1F8B h) (coerce (list (code-char #x1F83)) 'string))
    (setf (gethash #x1F8C h) (coerce (list (code-char #x1F84)) 'string))
    (setf (gethash #x1F8D h) (coerce (list (code-char #x1F85)) 'string))
    (setf (gethash #x1F8E h) (coerce (list (code-char #x1F86)) 'string))
    (setf (gethash #x1F8F h) (coerce (list (code-char #x1F87)) 'string))
    (setf (gethash #x1F98 h) (coerce (list (code-char #x1F90)) 'string))
    (setf (gethash #x1F99 h) (coerce (list (code-char #x1F91)) 'string))
    (setf (gethash #x1F9A h) (coerce (list (code-char #x1F92)) 'string))
    (setf (gethash #x1F9B h) (coerce (list (code-char #x1F93)) 'string))
    (setf (gethash #x1F9C h) (coerce (list (code-char #x1F94)) 'string))
    (setf (gethash #x1F9D h) (coerce (list (code-char #x1F95)) 'string))
    (setf (gethash #x1F9E h) (coerce (list (code-char #x1F96)) 'string))
    (setf (gethash #x1F9F h) (coerce (list (code-char #x1F97)) 'string))
    (setf (gethash #x1FA8 h) (coerce (list (code-char #x1FA0)) 'string))
    (setf (gethash #x1FA9 h) (coerce (list (code-char #x1FA1)) 'string))
    (setf (gethash #x1FAA h) (coerce (list (code-char #x1FA2)) 'string))
    (setf (gethash #x1FAB h) (coerce (list (code-char #x1FA3)) 'string))
    (setf (gethash #x1FAC h) (coerce (list (code-char #x1FA4)) 'string))
    (setf (gethash #x1FAD h) (coerce (list (code-char #x1FA5)) 'string))
    (setf (gethash #x1FAE h) (coerce (list (code-char #x1FA6)) 'string))
    (setf (gethash #x1FAF h) (coerce (list (code-char #x1FA7)) 'string))
    (setf (gethash #x1FBC h) (coerce (list (code-char #x1FB3)) 'string))
    (setf (gethash #x1FCC h) (coerce (list (code-char #x1FC3)) 'string))
    (setf (gethash #x1FFC h) (coerce (list (code-char #x1FF3)) 'string))
    (setf (gethash #x2126 h) (coerce (list (code-char #x3C9)) 'string))
    (setf (gethash #x212A h) (coerce (list (code-char #x6B)) 'string))
    (setf (gethash #x212B h) (coerce (list (code-char #xE5)) 'string))
    (setf (gethash #x2160 h) (coerce (list (code-char #x2170)) 'string))
    (setf (gethash #x2161 h) (coerce (list (code-char #x2171)) 'string))
    (setf (gethash #x2162 h) (coerce (list (code-char #x2172)) 'string))
    (setf (gethash #x2163 h) (coerce (list (code-char #x2173)) 'string))
    (setf (gethash #x2164 h) (coerce (list (code-char #x2174)) 'string))
    (setf (gethash #x2165 h) (coerce (list (code-char #x2175)) 'string))
    (setf (gethash #x2166 h) (coerce (list (code-char #x2176)) 'string))
    (setf (gethash #x2167 h) (coerce (list (code-char #x2177)) 'string))
    (setf (gethash #x2168 h) (coerce (list (code-char #x2178)) 'string))
    (setf (gethash #x2169 h) (coerce (list (code-char #x2179)) 'string))
    (setf (gethash #x216A h) (coerce (list (code-char #x217A)) 'string))
    (setf (gethash #x216B h) (coerce (list (code-char #x217B)) 'string))
    (setf (gethash #x216C h) (coerce (list (code-char #x217C)) 'string))
    (setf (gethash #x216D h) (coerce (list (code-char #x217D)) 'string))
    (setf (gethash #x216E h) (coerce (list (code-char #x217E)) 'string))
    (setf (gethash #x216F h) (coerce (list (code-char #x217F)) 'string))
    (setf (gethash #x24B6 h) (coerce (list (code-char #x24D0)) 'string))
    (setf (gethash #x24B7 h) (coerce (list (code-char #x24D1)) 'string))
    (setf (gethash #x24B8 h) (coerce (list (code-char #x24D2)) 'string))
    (setf (gethash #x24B9 h) (coerce (list (code-char #x24D3)) 'string))
    (setf (gethash #x24BA h) (coerce (list (code-char #x24D4)) 'string))
    (setf (gethash #x24BB h) (coerce (list (code-char #x24D5)) 'string))
    (setf (gethash #x24BC h) (coerce (list (code-char #x24D6)) 'string))
    (setf (gethash #x24BD h) (coerce (list (code-char #x24D7)) 'string))
    (setf (gethash #x24BE h) (coerce (list (code-char #x24D8)) 'string))
    (setf (gethash #x24BF h) (coerce (list (code-char #x24D9)) 'string))
    (setf (gethash #x24C0 h) (coerce (list (code-char #x24DA)) 'string))
    (setf (gethash #x24C1 h) (coerce (list (code-char #x24DB)) 'string))
    (setf (gethash #x24C2 h) (coerce (list (code-char #x24DC)) 'string))
    (setf (gethash #x24C3 h) (coerce (list (code-char #x24DD)) 'string))
    (setf (gethash #x24C4 h) (coerce (list (code-char #x24DE)) 'string))
    (setf (gethash #x24C5 h) (coerce (list (code-char #x24DF)) 'string))
    (setf (gethash #x24C6 h) (coerce (list (code-char #x24E0)) 'string))
    (setf (gethash #x24C7 h) (coerce (list (code-char #x24E1)) 'string))
    (setf (gethash #x24C8 h) (coerce (list (code-char #x24E2)) 'string))
    (setf (gethash #x24C9 h) (coerce (list (code-char #x24E3)) 'string))
    (setf (gethash #x24CA h) (coerce (list (code-char #x24E4)) 'string))
    (setf (gethash #x24CB h) (coerce (list (code-char #x24E5)) 'string))
    (setf (gethash #x24CC h) (coerce (list (code-char #x24E6)) 'string))
    (setf (gethash #x24CD h) (coerce (list (code-char #x24E7)) 'string))
    (setf (gethash #x24CE h) (coerce (list (code-char #x24E8)) 'string))
    (setf (gethash #x24CF h) (coerce (list (code-char #x24E9)) 'string))
    (setf (gethash #x2C2F h) (coerce (list (code-char #x2C5F)) 'string))
    (setf (gethash #xA7B8 h) (coerce (list (code-char #xA7B9)) 'string))
    (setf (gethash #xA7BA h) (coerce (list (code-char #xA7BB)) 'string))
    (setf (gethash #xA7BC h) (coerce (list (code-char #xA7BD)) 'string))
    (setf (gethash #xA7BE h) (coerce (list (code-char #xA7BF)) 'string))
    (setf (gethash #xA7C0 h) (coerce (list (code-char #xA7C1)) 'string))
    (setf (gethash #xA7C2 h) (coerce (list (code-char #xA7C3)) 'string))
    (setf (gethash #xA7C4 h) (coerce (list (code-char #xA794)) 'string))
    (setf (gethash #xA7C5 h) (coerce (list (code-char #x282)) 'string))
    (setf (gethash #xA7C6 h) (coerce (list (code-char #x1D8E)) 'string))
    (setf (gethash #xA7C7 h) (coerce (list (code-char #xA7C8)) 'string))
    (setf (gethash #xA7C9 h) (coerce (list (code-char #xA7CA)) 'string))
    (setf (gethash #xA7CB h) (coerce (list (code-char #x264)) 'string))
    (setf (gethash #xA7CC h) (coerce (list (code-char #xA7CD)) 'string))
    (setf (gethash #xA7CE h) (coerce (list (code-char #xA7CF)) 'string))
    (setf (gethash #xA7D0 h) (coerce (list (code-char #xA7D1)) 'string))
    (setf (gethash #xA7D2 h) (coerce (list (code-char #xA7D3)) 'string))
    (setf (gethash #xA7D4 h) (coerce (list (code-char #xA7D5)) 'string))
    (setf (gethash #xA7D6 h) (coerce (list (code-char #xA7D7)) 'string))
    (setf (gethash #xA7D8 h) (coerce (list (code-char #xA7D9)) 'string))
    (setf (gethash #xA7DA h) (coerce (list (code-char #xA7DB)) 'string))
    (setf (gethash #xA7DC h) (coerce (list (code-char #x19B)) 'string))
    (setf (gethash #xA7F5 h) (coerce (list (code-char #xA7F6)) 'string))
    (setf (gethash #x10570 h) (coerce (list (code-char #x10597)) 'string))
    (setf (gethash #x10571 h) (coerce (list (code-char #x10598)) 'string))
    (setf (gethash #x10572 h) (coerce (list (code-char #x10599)) 'string))
    (setf (gethash #x10573 h) (coerce (list (code-char #x1059A)) 'string))
    (setf (gethash #x10574 h) (coerce (list (code-char #x1059B)) 'string))
    (setf (gethash #x10575 h) (coerce (list (code-char #x1059C)) 'string))
    (setf (gethash #x10576 h) (coerce (list (code-char #x1059D)) 'string))
    (setf (gethash #x10577 h) (coerce (list (code-char #x1059E)) 'string))
    (setf (gethash #x10578 h) (coerce (list (code-char #x1059F)) 'string))
    (setf (gethash #x10579 h) (coerce (list (code-char #x105A0)) 'string))
    (setf (gethash #x1057A h) (coerce (list (code-char #x105A1)) 'string))
    (setf (gethash #x1057C h) (coerce (list (code-char #x105A3)) 'string))
    (setf (gethash #x1057D h) (coerce (list (code-char #x105A4)) 'string))
    (setf (gethash #x1057E h) (coerce (list (code-char #x105A5)) 'string))
    (setf (gethash #x1057F h) (coerce (list (code-char #x105A6)) 'string))
    (setf (gethash #x10580 h) (coerce (list (code-char #x105A7)) 'string))
    (setf (gethash #x10581 h) (coerce (list (code-char #x105A8)) 'string))
    (setf (gethash #x10582 h) (coerce (list (code-char #x105A9)) 'string))
    (setf (gethash #x10583 h) (coerce (list (code-char #x105AA)) 'string))
    (setf (gethash #x10584 h) (coerce (list (code-char #x105AB)) 'string))
    (setf (gethash #x10585 h) (coerce (list (code-char #x105AC)) 'string))
    (setf (gethash #x10586 h) (coerce (list (code-char #x105AD)) 'string))
    (setf (gethash #x10587 h) (coerce (list (code-char #x105AE)) 'string))
    (setf (gethash #x10588 h) (coerce (list (code-char #x105AF)) 'string))
    (setf (gethash #x10589 h) (coerce (list (code-char #x105B0)) 'string))
    (setf (gethash #x1058A h) (coerce (list (code-char #x105B1)) 'string))
    (setf (gethash #x1058C h) (coerce (list (code-char #x105B3)) 'string))
    (setf (gethash #x1058D h) (coerce (list (code-char #x105B4)) 'string))
    (setf (gethash #x1058E h) (coerce (list (code-char #x105B5)) 'string))
    (setf (gethash #x1058F h) (coerce (list (code-char #x105B6)) 'string))
    (setf (gethash #x10590 h) (coerce (list (code-char #x105B7)) 'string))
    (setf (gethash #x10591 h) (coerce (list (code-char #x105B8)) 'string))
    (setf (gethash #x10592 h) (coerce (list (code-char #x105B9)) 'string))
    (setf (gethash #x10594 h) (coerce (list (code-char #x105BB)) 'string))
    (setf (gethash #x10595 h) (coerce (list (code-char #x105BC)) 'string))
    (setf (gethash #x10D50 h) (coerce (list (code-char #x10D70)) 'string))
    (setf (gethash #x10D51 h) (coerce (list (code-char #x10D71)) 'string))
    (setf (gethash #x10D52 h) (coerce (list (code-char #x10D72)) 'string))
    (setf (gethash #x10D53 h) (coerce (list (code-char #x10D73)) 'string))
    (setf (gethash #x10D54 h) (coerce (list (code-char #x10D74)) 'string))
    (setf (gethash #x10D55 h) (coerce (list (code-char #x10D75)) 'string))
    (setf (gethash #x10D56 h) (coerce (list (code-char #x10D76)) 'string))
    (setf (gethash #x10D57 h) (coerce (list (code-char #x10D77)) 'string))
    (setf (gethash #x10D58 h) (coerce (list (code-char #x10D78)) 'string))
    (setf (gethash #x10D59 h) (coerce (list (code-char #x10D79)) 'string))
    (setf (gethash #x10D5A h) (coerce (list (code-char #x10D7A)) 'string))
    (setf (gethash #x10D5B h) (coerce (list (code-char #x10D7B)) 'string))
    (setf (gethash #x10D5C h) (coerce (list (code-char #x10D7C)) 'string))
    (setf (gethash #x10D5D h) (coerce (list (code-char #x10D7D)) 'string))
    (setf (gethash #x10D5E h) (coerce (list (code-char #x10D7E)) 'string))
    (setf (gethash #x10D5F h) (coerce (list (code-char #x10D7F)) 'string))
    (setf (gethash #x10D60 h) (coerce (list (code-char #x10D80)) 'string))
    (setf (gethash #x10D61 h) (coerce (list (code-char #x10D81)) 'string))
    (setf (gethash #x10D62 h) (coerce (list (code-char #x10D82)) 'string))
    (setf (gethash #x10D63 h) (coerce (list (code-char #x10D83)) 'string))
    (setf (gethash #x10D64 h) (coerce (list (code-char #x10D84)) 'string))
    (setf (gethash #x10D65 h) (coerce (list (code-char #x10D85)) 'string))
    (setf (gethash #x16E40 h) (coerce (list (code-char #x16E60)) 'string))
    (setf (gethash #x16E41 h) (coerce (list (code-char #x16E61)) 'string))
    (setf (gethash #x16E42 h) (coerce (list (code-char #x16E62)) 'string))
    (setf (gethash #x16E43 h) (coerce (list (code-char #x16E63)) 'string))
    (setf (gethash #x16E44 h) (coerce (list (code-char #x16E64)) 'string))
    (setf (gethash #x16E45 h) (coerce (list (code-char #x16E65)) 'string))
    (setf (gethash #x16E46 h) (coerce (list (code-char #x16E66)) 'string))
    (setf (gethash #x16E47 h) (coerce (list (code-char #x16E67)) 'string))
    (setf (gethash #x16E48 h) (coerce (list (code-char #x16E68)) 'string))
    (setf (gethash #x16E49 h) (coerce (list (code-char #x16E69)) 'string))
    (setf (gethash #x16E4A h) (coerce (list (code-char #x16E6A)) 'string))
    (setf (gethash #x16E4B h) (coerce (list (code-char #x16E6B)) 'string))
    (setf (gethash #x16E4C h) (coerce (list (code-char #x16E6C)) 'string))
    (setf (gethash #x16E4D h) (coerce (list (code-char #x16E6D)) 'string))
    (setf (gethash #x16E4E h) (coerce (list (code-char #x16E6E)) 'string))
    (setf (gethash #x16E4F h) (coerce (list (code-char #x16E6F)) 'string))
    (setf (gethash #x16E50 h) (coerce (list (code-char #x16E70)) 'string))
    (setf (gethash #x16E51 h) (coerce (list (code-char #x16E71)) 'string))
    (setf (gethash #x16E52 h) (coerce (list (code-char #x16E72)) 'string))
    (setf (gethash #x16E53 h) (coerce (list (code-char #x16E73)) 'string))
    (setf (gethash #x16E54 h) (coerce (list (code-char #x16E74)) 'string))
    (setf (gethash #x16E55 h) (coerce (list (code-char #x16E75)) 'string))
    (setf (gethash #x16E56 h) (coerce (list (code-char #x16E76)) 'string))
    (setf (gethash #x16E57 h) (coerce (list (code-char #x16E77)) 'string))
    (setf (gethash #x16E58 h) (coerce (list (code-char #x16E78)) 'string))
    (setf (gethash #x16E59 h) (coerce (list (code-char #x16E79)) 'string))
    (setf (gethash #x16E5A h) (coerce (list (code-char #x16E7A)) 'string))
    (setf (gethash #x16E5B h) (coerce (list (code-char #x16E7B)) 'string))
    (setf (gethash #x16E5C h) (coerce (list (code-char #x16E7C)) 'string))
    (setf (gethash #x16E5D h) (coerce (list (code-char #x16E7D)) 'string))
    (setf (gethash #x16E5E h) (coerce (list (code-char #x16E7E)) 'string))
    (setf (gethash #x16E5F h) (coerce (list (code-char #x16E7F)) 'string))
    (setf (gethash #x16EA0 h) (coerce (list (code-char #x16EBB)) 'string))
    (setf (gethash #x16EA1 h) (coerce (list (code-char #x16EBC)) 'string))
    (setf (gethash #x16EA2 h) (coerce (list (code-char #x16EBD)) 'string))
    (setf (gethash #x16EA3 h) (coerce (list (code-char #x16EBE)) 'string))
    (setf (gethash #x16EA4 h) (coerce (list (code-char #x16EBF)) 'string))
    (setf (gethash #x16EA5 h) (coerce (list (code-char #x16EC0)) 'string))
    (setf (gethash #x16EA6 h) (coerce (list (code-char #x16EC1)) 'string))
    (setf (gethash #x16EA7 h) (coerce (list (code-char #x16EC2)) 'string))
    (setf (gethash #x16EA8 h) (coerce (list (code-char #x16EC3)) 'string))
    (setf (gethash #x16EA9 h) (coerce (list (code-char #x16EC4)) 'string))
    (setf (gethash #x16EAA h) (coerce (list (code-char #x16EC5)) 'string))
    (setf (gethash #x16EAB h) (coerce (list (code-char #x16EC6)) 'string))
    (setf (gethash #x16EAC h) (coerce (list (code-char #x16EC7)) 'string))
    (setf (gethash #x16EAD h) (coerce (list (code-char #x16EC8)) 'string))
    (setf (gethash #x16EAE h) (coerce (list (code-char #x16EC9)) 'string))
    (setf (gethash #x16EAF h) (coerce (list (code-char #x16ECA)) 'string))
    (setf (gethash #x16EB0 h) (coerce (list (code-char #x16ECB)) 'string))
    (setf (gethash #x16EB1 h) (coerce (list (code-char #x16ECC)) 'string))
    (setf (gethash #x16EB2 h) (coerce (list (code-char #x16ECD)) 'string))
    (setf (gethash #x16EB3 h) (coerce (list (code-char #x16ECE)) 'string))
    (setf (gethash #x16EB4 h) (coerce (list (code-char #x16ECF)) 'string))
    (setf (gethash #x16EB5 h) (coerce (list (code-char #x16ED0)) 'string))
    (setf (gethash #x16EB6 h) (coerce (list (code-char #x16ED1)) 'string))
    (setf (gethash #x16EB7 h) (coerce (list (code-char #x16ED2)) 'string))
    (setf (gethash #x16EB8 h) (coerce (list (code-char #x16ED3)) 'string))
    h))
