;;;; src/css/background-position.lisp
(in-package #:weft.css)

(defun background-position-parse-number-unit (tok)
  (let* ((lower tok)
         (tlen (length lower)))
    (let ((pos 0))
      ;; optional sign
      (when (and (< pos tlen)
                 (or (char= (char lower pos) #\-)
                     (char= (char lower pos) #\+)))
        (incf pos))
      ;; must start with digit or dot
      (when (or (>= pos tlen)
                (not (or (digit-char-p (char lower pos))
                         (char= (char lower pos) #\.))))
        (return-from background-position-parse-number-unit :invalid))
      ;; integer part
      (loop while (and (< pos tlen) (digit-char-p (char lower pos)))
            do (incf pos))
      ;; optional fractional part
      (when (and (< pos tlen) (char= (char lower pos) #\.))
        (incf pos)
        (loop while (and (< pos tlen) (digit-char-p (char lower pos)))
              do (incf pos)))
      ;; optional exponent
      (when (and (< pos tlen) (char= (char lower pos) #\e))
        (let ((next (1+ pos)))
          (when (and (< next tlen)
                     (or (digit-char-p (char lower next))
                         (and (< (1+ next) tlen)
                              (or (char= (char lower next) #\-)
                                  (char= (char lower next) #\+))
                              (digit-char-p (char lower (1+ next))))))
            (incf pos)
            (when (and (< pos tlen)
                       (or (char= (char lower pos) #\-)
                           (char= (char lower pos) #\+)))
              (incf pos))
            (when (or (>= pos tlen) (not (digit-char-p (char lower pos))))
              (return-from background-position-parse-number-unit :invalid))
            (loop while (and (< pos tlen) (digit-char-p (char lower pos)))
                  do (incf pos)))))
      (let* ((num-str (subseq lower 0 pos))
             (unit-str (subseq lower pos))
             (value (safe-number num-str)))
        (if (string= unit-str "")
            (if (= value 0)
                (list (float value 0d0) "")
                :invalid)
            (if (member unit-str
                        '("px" "em" "rem" "ex" "ch"
                          "vw" "vh" "vmin" "vmax"
                          "cm" "mm" "in" "pt" "pc" "q"
                          "%")
                        :test #'string=)
                (list (float value 0d0) unit-str)
                :invalid))))))

(define-value-parser "background-position" (s)
  (let* ((trimmed (css-trim s))
         (lower (ascii-downcase trimmed))
         (len (length lower)))
    (if (zerop len)
        :invalid
        (flet ((parse-token (tok)
                 (cond
                   ((string= tok "left") '(0.0 "%"))
                   ((string= tok "right") '(100.0 "%"))
                   ((string= tok "top") '(0.0 "%"))
                   ((string= tok "bottom") '(100.0 "%"))
                   ((string= tok "center") '(50.0 "%"))
                   (t (background-position-parse-number-unit tok)))))
          ;; split into tokens
          (let ((tokens '())
                (start 0))
            (loop while (< start len)
                  do (let ((end (position #\Space lower :start start)))
                       (if (null end)
                           (progn (push (subseq lower start) tokens)
                                  (setf start len))
                           (progn (when (> end start)
                                    (push (subseq lower start end) tokens))
                                  (setf start (1+ end))))))
            (let* ((tokens (nreverse tokens))
                   (ntokens (length tokens)))
              (if (or (< ntokens 1) (> ntokens 2))
                  :invalid
                  (let* ((x (parse-token (first tokens)))
                         (y (if (= ntokens 2)
                                (parse-token (second tokens))
                                '(50.0 "%"))))
                    (if (or (eq x :invalid) (eq y :invalid))
                        :invalid
                        (list x y))))))))))