;;;; src/css/color.lisp — CSS <color> value parser
(in-package #:weft.css)

(define-value-parser "color" (s)
  (let* ((s (css-trim s))
         (s (ascii-downcase s))
         (len (length s)))
    (labels
        ((digit-val (c)
           (if (digit-char-p c)
               (digit-char-p c)
               (+ 10 (- (char-code c) (char-code #\a)))))
         (hex-digit-p (c)
           (or (digit-char-p c 16)
               (and (char>= c #\a) (char<= c #\f))))
         (unhex2 (str &optional (start 0))
           (+ (* (digit-val (char str start)) 16)
              (digit-val (char str (1+ start)))))
         (nibble-val (c)
           (let ((v (digit-val c)))
             (+ (* v 16) v)))
         (round4 (x)
           (/ (round (* x 10000)) 10000.0))
         (clamp (v lo hi)
           (max lo (min hi v)))
         (try-parse-num (str)
           (ignore-errors (read-from-string str)))
         ;; Hex parsing
         (parse-hex ()
           (let* ((body (subseq s 1))
                  (blen (length body)))
             (unless (and (> blen 0) (every #'hex-digit-p body))
               (return-from parse-hex :invalid))
             (case blen
               (3 (list (nibble-val (char body 0))
                        (nibble-val (char body 1))
                        (nibble-val (char body 2))
                        1.0))
               (4 (list (nibble-val (char body 0))
                        (nibble-val (char body 1))
                        (nibble-val (char body 2))
                        (round4 (/ (nibble-val (char body 3)) 255.0))))
               (6 (list (unhex2 body 0)
                        (unhex2 body 2)
                        (unhex2 body 4)
                        1.0))
               (8 (list (unhex2 body 0)
                        (unhex2 body 2)
                        (unhex2 body 4)
                        (round4 (/ (unhex2 body 6) 255.0))))
               (t :invalid))))
         ;; Split comma/slash-separated components
         (split-comps (str)
           (let* ((n (length str))
                  (buf (make-string n)))
             (dotimes (i n)
               (setf (char buf i)
                     (if (or (char= (char str i) #\,)
                             (char= (char str i) #\/))
                         #\Space
                         (char str i))))
             (let ((parts '()) (start nil))
               (loop for i from 0 below n do
                 (cond ((and (null start) (not (char= (char buf i) #\Space)))
                        (setf start i))
                       ((and (not (null start)) (char= (char buf i) #\Space))
                        (push (subseq buf start i) parts)
                        (setf start nil))))
               (when start (push (subseq buf start n) parts))
               (nreverse parts))))
         ;; Parse RGB component: "50%" -> (* 2.55 pct), else number
         (parse-rgb-comp (str)
           (let ((l (length str)))
             (if (and (> l 0) (char= (char str (1- l)) #\%))
                 (let ((v (try-parse-num (subseq str 0 (1- l)))))
                   (when v (* v 2.55)))
                 (try-parse-num str))))
         ;; Parse alpha component: "50%" -> 0.5, else float
         (parse-alpha (str)
           (let ((l (length str)))
             (if (and (> l 0) (char= (char str (1- l)) #\%))
                 (let ((v (try-parse-num (subseq str 0 (1- l)))))
                   (when v (/ v 100.0)))
                 (try-parse-num str))))
         ;; RGB/RGBA parser
         (parse-rgb ()
           ;; A missing close paren is not fatal: at EOF an open function auto-closes
           ;; (CSS Syntax §5.4.9), so `rgb(0, 128, 0` yields the components up to end.
           (let* ((open (position #\( s))
                  (close (when open (position #\) s :start open)))
                  (content (and open (subseq s (1+ open) (or close (length s)))))
                  (parts (and content (split-comps content)))
                  (n (length parts)))
             (unless (or (= n 3) (= n 4))
               (return-from parse-rgb :invalid))
             (let* ((r (parse-rgb-comp (elt parts 0)))
                    (g (parse-rgb-comp (elt parts 1)))
                    (b (parse-rgb-comp (elt parts 2)))
                    (a (if (= n 4)
                           (let ((av (parse-alpha (elt parts 3))))
                             (when av (clamp (round4 av) 0.0 1.0)))
                           1.0)))
               (if (and r g b a)
                   (list (clamp (round r) 0 255)
                         (clamp (round g) 0 255)
                         (clamp (round b) 0 255)
                         (float a))
                   :invalid))))
         ;; HSL algorithm
         (hsl-to-rgb (h s l)
           (let* ((s (/ s 100.0))
                  (l (/ l 100.0))
                  (c (* (- 1 (abs (- (* 2 l) 1))) s))
                  (x (* c (- 1 (abs (- (mod (/ h 60.0) 2) 1)))))
                  (m (- l (/ c 2)))
                  (h-sec (floor h 60)))
             (multiple-value-bind (r1 g1 b1)
                 (case h-sec
                   (0 (values c x 0))
                   (1 (values x c 0))
                   (2 (values 0 c x))
                   (3 (values 0 x c))
                   (4 (values x 0 c))
                   (5 (values c 0 x))
                   (t (values 0 0 0)))
               (values (round (* (+ r1 m) 255))
                       (round (* (+ g1 m) 255))
                       (round (* (+ b1 m) 255))))))
         ;; HSL/HSLA parser
         (parse-hsl ()
           (let* ((open (position #\( s))
                  (close (when open (position #\) s :start open)))
                  (content (and close (> close open) (subseq s (1+ open) close)))
                  (parts (and content (split-comps content)))
                  (n (length parts)))
             (unless (or (= n 3) (= n 4))
               (return-from parse-hsl :invalid))
             (let* ((h-str (elt parts 0))
                    (h-len (length h-str))
                    ;; Strip trailing "deg" if present
                    (h-clean (if (and (>= h-len 3)
                                      (string= (subseq h-str (- h-len 3)) "deg"))
                                 (subseq h-str 0 (- h-len 3))
                                 h-str))
                    (h-val (try-parse-num h-clean))
                    ;; S and L: must be percentages
                    (s-str (elt parts 1))
                    (l-str (elt parts 2))
                    (s-val (and (> (length s-str) 0)
                                (char= (char s-str (1- (length s-str))) #\%)
                                (try-parse-num (subseq s-str 0 (1- (length s-str))))))
                    (l-val (and (> (length l-str) 0)
                                (char= (char l-str (1- (length l-str))) #\%)
                                (try-parse-num (subseq l-str 0 (1- (length l-str))))))
                    (a (if (= n 4)
                           (let ((av (parse-alpha (elt parts 3))))
                             (when av (clamp (round4 av) 0.0 1.0)))
                           1.0)))
               (if (and h-val s-val l-val a)
                   (multiple-value-bind (r g b)
                       (hsl-to-rgb (mod h-val 360) (clamp s-val 0 100) (clamp l-val 0 100))
                     (list (clamp r 0 255)
                           (clamp g 0 255)
                           (clamp b 0 255)
                           (float a)))
                   :invalid)))))
      ;; Main dispatch
      (cond
        ((string= s "transparent")
         (list 0 0 0 0.0))
        ((gethash s *named-colors*)
         (let ((rgb (gethash s *named-colors*)))
           (list (first rgb) (second rgb) (third rgb) 1.0)))
        ((and (> len 0) (char= (char s 0) #\#))
         (parse-hex))
        ((and (> len 4) (or (string= (subseq s 0 5) "rgba(")
                            (string= (subseq s 0 4) "rgb(")))
         (parse-rgb))
        ((and (> len 4) (or (string= (subseq s 0 5) "hsla(")
                            (string= (subseq s 0 4) "hsl(")))
         (parse-hsl))
        (t :invalid)))))