;;;; src/css/flex.lisp — <flex> shorthand -> (grow shrink basis).
(in-package #:weft.css)
(define-value-parser "flex" (s)
  (let* ((tt (ascii-downcase (css-trim s)))
         (parts (let ((out '()) (b (make-string-output-stream)) (any nil))
                  (loop for c across tt do
                    (if (member c '(#\Space #\Tab #\Newline)) (when any (push (get-output-stream-string b) out) (setf any nil b (make-string-output-stream)))
                        (progn (write-char c b) (setf any t))))
                  (when any (push (get-output-stream-string b) out))
                  (nreverse out))))
    (cond
      ((string= tt "none") (list 0.0 0.0 "auto"))
      ((null parts) :invalid)
      ((= 1 (length parts))
       (cond ((string= (first parts) "auto") (list 1.0 1.0 "auto"))
             (t (let ((n (ignore-errors (read-from-string (first parts)))))
                  (if (numberp n) (list (float n) 1.0 "0%") :invalid)))))
      ((>= (length parts) 2)
       (let ((g (ignore-errors (read-from-string (first parts))))
             (sh (ignore-errors (read-from-string (second parts)))))
         (if (and (numberp g) (numberp sh))
             (list (float g) (float sh) (if (third parts) (third parts) "0%"))
             :invalid)))
      (t :invalid))))
