;;;; src/css/line-height.lisp
(in-package #:weft.css)
(define-value-parser "line-height" (s)
  (let ((trimmed (css-trim s))
        (lowered (ascii-downcase trimmed)))
    (cond ((string= lowered "normal") '("normal"))
          ((string= lowered "") :invalid)
          (t (multiple-value-bind (val pos)
                 (ignore-errors (read-from-string lowered))
               (if (numberp val)
                   (let ((rest (subseq lowered pos)))
                     (cond ((string= rest "") (list (float val 1.0f0)))
                           ((string= rest "px") (list (float val 1.0f0) "px"))
                           (t :invalid)))
                   :invalid))))))
