;;;; src/css/line-height.lisp
(in-package #:weft.css)
(define-value-parser "line-height" (s)
  (let* ((trimmed (css-trim s))
         (lowered (ascii-downcase trimmed)))
    (cond
      ((string= lowered "normal") '("normal"))
      ((string= lowered "") :invalid)
      ((and (>= (length lowered) 2)
            (string= (subseq lowered (- (length lowered) 2)) "px"))
       (let* ((num-str (subseq lowered 0 (- (length lowered) 2))))
         (if (string= num-str "")
             :invalid
             (multiple-value-bind (val pos)
                 (ignore-errors (read-from-string num-str))
               (if (and (numberp val) (= pos (length num-str)))
                   (list (float val 1.0f0) "px")
                   :invalid)))))
      (t (multiple-value-bind (val pos)
             (ignore-errors (read-from-string lowered))
           (if (and (numberp val) (= pos (length lowered)))
               (list (float val 1.0f0))
               :invalid))))))
