;;;; src/css/transform.lisp — transform list -> list of (fn arg...).
(in-package #:weft.css)
(define-value-parser "transform" (s)
  (let ((tt (ascii-downcase (css-trim s))))
    (if (string= tt "none") (list "none")
        (let ((out '()) (i 0) (n (length tt)) (bad nil))
          (loop while (and (< i n) (not bad)) do
            (loop while (and (< i n) (member (char tt i) '(#\Space #\Tab #\Newline))) do (incf i))
            (when (< i n)
              (let ((name-start i))
                (loop while (and (< i n) (alphanumericp (char tt i))) do (incf i))
                (if (and (< i n) (char= (char tt i) #\() (> i name-start))
                    (let ((fn (subseq tt name-start i)) (arg-start (1+ i)))
                      (incf i)
                      (loop while (and (< i n) (not (char= (char tt i) #\)))) do (incf i))
                      (let ((args (mapcar (lambda (a) (string-trim '(#\Space) a))
                                          (remove "" (split-comma (subseq tt arg-start i)) :test #'string=))))
                        (push (cons fn args) out))
                      (when (< i n) (incf i)))
                    (setf bad t)))))
          (if (or bad (null out)) :invalid (nreverse out))))))
(defun split-comma (s)
  (let ((out '()) (b (make-string-output-stream)) (any nil))
    (loop for c across s do
      (if (char= c #\,) (progn (push (get-output-stream-string b) out) (setf b (make-string-output-stream) any nil))
          (progn (write-char c b) (setf any t))))
    (let ((last (get-output-stream-string b))) (when (or any (plusp (length last))) (push last out)))
    (nreverse out)))
